//! The Tauri shell.
//!
//! This crate only wires things together: it builds the app, holds shared
//! state, exposes thin commands and streams files through `book://`.
//! Anything that is a rule about books or libraries belongs in a
//! `libreri-*` crate (see docs/code-structure.md).

mod commands;
mod dto;
mod error;
mod events;
mod protocol;
mod settings_store;
mod state;

use state::AppState;
use tauri::Manager;

/// Builds the typed command/event registry shared by the app and by the
/// TypeScript bindings generator.
pub fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            commands::app::app_info,
            commands::settings::get_settings,
            commands::settings::set_theme,
            commands::settings::forget_recent_library,
            commands::library::create_library,
            commands::library::open_library,
            commands::library::close_library,
            commands::library::current_library,
            commands::library::inspect_folder,
            commands::library::rescan_library,
            commands::library::rebuild_library_index,
            commands::library::cancel_job,
            commands::books::list_books,
            commands::books::get_book,
            commands::books::library_facets,
            commands::books::update_book,
            commands::books::set_book_state,
            commands::books::move_books,
            commands::books::trash_books,
            commands::books::save_cover,
            commands::books::open_book_externally,
            commands::books::reveal_book,
            commands::folders::list_folders,
            commands::folders::create_folder,
            commands::folders::rename_folder,
            commands::folders::move_folder,
            commands::folders::trash_folder,
            commands::folders::reveal_folder,
            commands::folders::import_paths,
        ])
        .events(tauri_specta::collect_events![
            events::JobEventPayload,
            events::LibraryChanged,
            events::ImportFinished,
        ])
}

/// Starts the desktop app.
pub fn run() {
    let builder = specta_builder();

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(builder.invoke_handler())
        .register_uri_scheme_protocol("book", protocol::handle)
        .setup(move |app| {
            builder.mount_events(app);
            let state = AppState::initialise(app.handle())?;
            app.manage(state);
            app.state::<AppState>().reopen_last_library();
            Ok(())
        })
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::Destroyed = event {
                // Close the library cleanly so the database is checkpointed
                // and the lock released.
                if let Some(state) = window.app_handle().try_state::<AppState>() {
                    state.close_library();
                }
            }
        })
        .run(tauri::generate_context!())
        .expect("error while running Libreri");
}

#[cfg(test)]
mod tests {
    /// Regenerates `src/lib/ipc/bindings.ts`. CI fails if the committed file
    /// is out of date, so Rust and TypeScript types never drift apart.
    #[test]
    fn export_typescript_bindings() {
        super::specta_builder()
            .export(
                specta_typescript::Typescript::default()
                    .header("// Generated by tauri-specta from the Rust commands. Do not edit.\n// Regenerate with: pnpm gen:ipc\n"),
                "../src/lib/ipc/bindings.ts",
            )
            .expect("failed to export TypeScript bindings");
    }
}
