// Generated by tauri-specta from the Rust commands. Do not edit.
// Regenerate with: pnpm gen:ipc

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Version and platform, for the About screen and diagnostics. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**
	 *  Opens a web link in the system browser. Only `http`, `https` and
	 *  `mailto` links are allowed.
	 */
	openExternalUrl: (url: string) => typedError<null, AppError>(__TAURI_INVOKE("open_external_url", { url })),
	getSettings: () => __TAURI_INVOKE<SettingsDto>("get_settings"),
	setTheme: (theme: Theme) => typedError<SettingsDto, AppError>(__TAURI_INVOKE("set_theme", { theme })),
	setAccent: (accent: string | null) => typedError<SettingsDto, AppError>(__TAURI_INVOKE("set_accent", { accent })),
	forgetRecentLibrary: (path: string) => typedError<SettingsDto, AppError>(__TAURI_INVOKE("forget_recent_library", { path })),
	/**
	 *  What a book would be looked up by (its identifiers, or ones found in
	 *  its pages), to fill the search form.
	 */
	detailsQuery: (id: string) => typedError<Query, AppError>(__TAURI_INVOKE("details_query", { id })),
	/**
	 *  Asks the online sources about a book. `query` is the reader's own
	 *  search; without it the book's details are used.
	 */
	findDetails: (id: string, query: {
	isbn?: string | null,
	doi?: string | null,
	arxivId?: string | null,
	title?: string | null,
	author?: string | null,
	/**
	 *  What kind of item it is, if known, so a comic goes to ComicVine and
	 *  a paper to Crossref.
	 */
	contentType?: ContentType | null,
} | null) => typedError<Lookup, AppError>(__TAURI_INVOKE("find_details", { id, query })),
	/**  Saves the details picked in the merge screen, and the picked cover. */
	applyDetails: (id: string, metadata: BookMetadata, coverUrl: string | null) => typedError<AppliedDetails, AppError>(__TAURI_INVOKE("apply_details", { id, metadata, coverUrl })),
	/**
	 *  A cover from a source as a data: URL, so the interface can show it
	 *  without loading images from the internet itself.
	 */
	coverPreview: (url: string) => typedError<string, AppError>(__TAURI_INVOKE("cover_preview", { url })),
	/**
	 *  Fills in missing details of many books in the background. Returns the
	 *  job id; the result arrives as a `DetailsFilled` event.
	 */
	fillMissingDetails: (ids: string[]) => typedError<string, AppError>(__TAURI_INVOKE("fill_missing_details", { ids })),
	getOnlineSettings: () => __TAURI_INVOKE<OnlineSettingsDto>("get_online_settings"),
	setOnlineSettings: (change: OnlineChange) => typedError<OnlineSettingsDto, AppError>(__TAURI_INVOKE("set_online_settings", { change })),
	/**
	 *  Saves (or, with `None`, removes) the reader's key for a source. Saving
	 *  a key also turns the source on.
	 */
	setSourceKey: (source: Source, key: string | null) => typedError<OnlineSettingsDto, AppError>(__TAURI_INVOKE("set_source_key", { source, key })),
	/**
	 *  Reads a barcode from a picture (a camera frame), sent as a data: URL or
	 *  base64. Returns nothing if there is no readable barcode.
	 */
	scanPicture: (data: string) => typedError<{
	code: string,
	isbn13: string | null,
} | null, AppError>(__TAURI_INVOKE("scan_picture", { data })),
	/**  Reads a barcode from a picture file the reader chose. */
	scanPictureFile: (path: string) => typedError<{
	code: string,
	isbn13: string | null,
} | null, AppError>(__TAURI_INVOKE("scan_picture_file", { path })),
	/**
	 *  Starts the phone page (replacing any earlier one). Scans arrive as
	 *  `PhoneScan` events.
	 */
	startPhoneScan: () => typedError<PhonePairingDto, AppError>(__TAURI_INVOKE("start_phone_scan")),
	/**  Stops the phone page. */
	stopPhoneScan: () => __TAURI_INVOKE<void>("stop_phone_scan"),
	/**  Creates a new library in `path` and opens it. */
	createLibrary: (path: string, name: string | null) => typedError<LibrarySummary, AppError>(__TAURI_INVOKE("create_library", { path, name })),
	/**
	 *  Opens an existing library. `force` takes over a lock left by another
	 *  computer, after the user has confirmed.
	 */
	openLibrary: (path: string, force: boolean) => typedError<LibrarySummary, AppError>(__TAURI_INVOKE("open_library", { path, force })),
	/**  Closes the library (writing out the database can take a moment). */
	closeLibrary: () => __TAURI_INVOKE<void>("close_library"),
	currentLibrary: () => __TAURI_INVOKE<{
	id: string,
	name: string,
	path: string,
	/**  `u32` is plenty for a book count and maps to a plain TypeScript number. */
	bookCount: number,
} | null>("current_library"),
	/**  Tells the Welcome screen what the chosen folder contains. */
	inspectFolder: (path: string) => __TAURI_INVOKE<FolderKind>("inspect_folder", { path }),
	/**
	 *  Checks the library folder for changes now (the watcher does this
	 *  automatically; this is the manual "Refresh").
	 */
	rescanLibrary: () => typedError<string | null, AppError>(__TAURI_INVOKE("rescan_library")),
	/**  Rebuilds the database from the book files and JSON sidecars. */
	rebuildLibraryIndex: () => typedError<string, AppError>(__TAURI_INVOKE("rebuild_library_index")),
	/**  Stops a running import or scan at the next file. */
	cancelJob: (id: string) => __TAURI_INVOKE<boolean>("cancel_job", { id }),
	listBooks: (query: BookQuery) => typedError<BookDto[], AppError>(__TAURI_INVOKE("list_books", { query })),
	getBook: (id: string) => typedError<BookDto, AppError>(__TAURI_INVOKE("get_book", { id })),
	libraryFacets: () => typedError<FacetsDto, AppError>(__TAURI_INVOKE("library_facets")),
	/**
	 *  Saves edited details. Refuses invalid ISBNs, an empty title, etc. with a
	 *  message that says what to fix.
	 */
	updateBook: (id: string, metadata: BookMetadata) => typedError<BookDto, AppError>(__TAURI_INVOKE("update_book", { id, metadata })),
	/**  Saves the current profile's reading status, rating and favourite flag. */
	setBookState: (id: string, user: BookUserState) => typedError<BookDto, AppError>(__TAURI_INVOKE("set_book_state", { id, user })),
	/**  Moves books into a folder (relative to `Books/`). Returns how many moved. */
	moveBooks: (ids: string[], folder: string) => typedError<number, AppError>(__TAURI_INVOKE("move_books", { ids, folder })),
	/**  Moves books to the system trash. Returns how many were removed. */
	trashBooks: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("trash_books", { ids })),
	/**
	 *  Stores a cover sent by the interface (base64 of a JPEG or PNG), such as
	 *  the first page of a PDF rendered with PDF.js.
	 */
	saveCover: (id: string, imageBase64: string) => typedError<null, AppError>(__TAURI_INVOKE("save_cover", { id, imageBase64 })),
	/**
	 *  Opens the book in the system's default app (until Libreri's own reader
	 *  arrives in Phase 2).
	 */
	openBookExternally: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("open_book_externally", { id })),
	/**  Shows the book's file in Finder / Explorer / the file manager. */
	revealBook: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("reveal_book", { id })),
	listFolders: () => typedError<FolderDto[], AppError>(__TAURI_INVOKE("list_folders")),
	/**  Creates `name` inside `parent`; returns the new folder's path. */
	createFolder: (parent: string, name: string) => typedError<string, AppError>(__TAURI_INVOKE("create_folder", { parent, name })),
	renameFolder: (path: string, name: string) => typedError<string, AppError>(__TAURI_INVOKE("rename_folder", { path, name })),
	moveFolder: (path: string, parent: string) => typedError<string, AppError>(__TAURI_INVOKE("move_folder", { path, parent })),
	/**
	 *  Moves a folder and its books to the system trash; returns the number of
	 *  books removed.
	 */
	trashFolder: (path: string) => typedError<number, AppError>(__TAURI_INVOKE("trash_folder", { path })),
	revealFolder: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("reveal_folder", { path })),
	/**
	 *  Starts importing files and folders into `folder`. Returns the job id;
	 *  progress arrives as job events and the summary as `ImportFinished`.
	 */
	importPaths: (paths: string[], folder: string, mode: ImportModeDto) => typedError<string, AppError>(__TAURI_INVOKE("import_paths", { paths, folder, mode })),
	/**  Where the current profile stopped reading (JSON), if anywhere. */
	getPosition: (id: string) => typedError<string | null, AppError>(__TAURI_INVOKE("get_position", { id })),
	savePosition: (id: string, locator: string, progress: number | null) => typedError<null, AppError>(__TAURI_INVOKE("save_position", { id, locator, progress })),
	listAnnotations: (id: string) => typedError<Annotation[], AppError>(__TAURI_INVOKE("list_annotations", { id })),
	/**  Adds or updates a highlight or bookmark; returns it with timestamps set. */
	saveAnnotation: (annotation: Annotation) => typedError<Annotation, AppError>(__TAURI_INVOKE("save_annotation", { annotation })),
	deleteAnnotation: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_annotation", { id })),
	/**  The Markdown notebook for a book, created on first use. */
	getNotebook: (id: string) => typedError<NotebookDto, AppError>(__TAURI_INVOKE("get_notebook", { id })),
	saveNotebook: (id: string, content: string) => typedError<NotebookDto, AppError>(__TAURI_INVOKE("save_notebook", { id, content })),
	/**  The reader tabs that were open last time (JSON written by the interface). */
	getSession: () => typedError<string | null, AppError>(__TAURI_INVOKE("get_session")),
	saveSession: (session: string) => typedError<null, AppError>(__TAURI_INVOKE("save_session", { session })),
	listProfiles: () => typedError<ProfileDto[], AppError>(__TAURI_INVOKE("list_profiles")),
	/**  The signed-in profile, or nothing when the profile picker should show. */
	currentSession: () => typedError<{
	profile: ProfileDto,
	/**  The profile's interface preferences (JSON written by the interface). */
	prefs: string,
	canEditLibrary: boolean,
	canManageProfiles: boolean,
	/**  False for guests: nothing they do is kept. */
	keepsData: boolean,
} | null, AppError>(__TAURI_INVOKE("current_session")),
	signIn: (id: string, pin: string | null) => typedError<SessionDto, AppError>(__TAURI_INVOKE("sign_in", { id, pin })),
	/**  Locks the library and goes back to the profile picker. */
	signOut: () => typedError<null, AppError>(__TAURI_INVOKE("sign_out")),
	createProfile: (profile: NewProfile) => typedError<ProfileDto, AppError>(__TAURI_INVOKE("create_profile", { profile })),
	updateProfile: (id: string, name: string, colour: string, kind: ProfileKind) => typedError<ProfileDto, AppError>(__TAURI_INVOKE("update_profile", { id, name, colour, kind })),
	/**
	 *  Sets, changes or removes a PIN. Returns the owner's new recovery code,
	 *  which the interface shows once.
	 */
	setProfilePin: (id: string, currentPin: string | null, newPin: string | null) => typedError<string | null, AppError>(__TAURI_INVOKE("set_profile_pin", { id, currentPin, newPin })),
	/**
	 *  Resets the owner's forgotten PIN with the recovery code and signs in.
	 *  Returns the next recovery code.
	 */
	recoverOwner: (recoveryCode: string, newPin: string) => typedError<string, AppError>(__TAURI_INVOKE("recover_owner", { recoveryCode, newPin })),
	deleteProfile: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_profile", { id })),
	setAllowedFolders: (id: string, folders: string[]) => typedError<ProfileDto, AppError>(__TAURI_INVOKE("set_allowed_folders", { id, folders })),
	/**  Saves the signed-in profile's interface preferences (JSON). */
	savePrefs: (prefs: string) => typedError<null, AppError>(__TAURI_INVOKE("save_prefs", { prefs })),
	listCollections: () => typedError<CollectionDto[], AppError>(__TAURI_INVOKE("list_collections")),
	/**  Adds (empty `id`) or updates a smart collection. */
	saveCollection: (id: string, name: string, query: BookQuery) => typedError<CollectionDto, AppError>(__TAURI_INVOKE("save_collection", { id, name, query })),
	deleteCollection: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_collection", { id })),
	/**  Applies one edit to many books. Returns how many changed. */
	bulkEditBooks: (ids: string[], edit: BulkEdit) => typedError<number, AppError>(__TAURI_INVOKE("bulk_edit_books", { ids, edit })),
	renameTag: (from: string, to: string) => typedError<number, AppError>(__TAURI_INVOKE("rename_tag", { from, to })),
	mergeTags: (sources: string[], into: string) => typedError<number, AppError>(__TAURI_INVOKE("merge_tags", { sources, into })),
	deleteTag: (tag: string) => typedError<number, AppError>(__TAURI_INVOKE("delete_tag", { tag })),
	renameCategory: (from: string, to: string) => typedError<number, AppError>(__TAURI_INVOKE("rename_category", { from, to })),
	deleteCategory: (path: string) => typedError<number, AppError>(__TAURI_INVOKE("delete_category", { path })),
	/**  Groups of tags that look like the same thing. */
	similarTags: () => typedError<TagCountDto[][], AppError>(__TAURI_INVOKE("similar_tags")),
	/**  All highlights, comments and bookmarks of the signed-in profile. */
	listAllNotes: () => typedError<NoteDto[], AppError>(__TAURI_INVOKE("list_all_notes")),
	/**  All Markdown notes in the signed-in profile's notes folder. */
	listNotebooks: () => typedError<NotebookEntryDto[], AppError>(__TAURI_INVOKE("list_notebooks")),
	readNote: (relPath: string) => typedError<string, AppError>(__TAURI_INVOKE("read_note", { relPath })),
	writeNote: (relPath: string, content: string) => typedError<null, AppError>(__TAURI_INVOKE("write_note", { relPath, content })),
	/**  Starts a note that is not about one book. Returns its path. */
	createNote: (title: string) => typedError<string, AppError>(__TAURI_INVOKE("create_note", { title })),
	/**  Shows the signed-in profile's notes folder in the file manager. */
	revealNotesFolder: () => typedError<string, AppError>(__TAURI_INVOKE("reveal_notes_folder")),
	/**  How much space the library's folders use, in bytes. */
	libraryStorage: () => typedError<StorageDto, AppError>(__TAURI_INVOKE("library_storage")),
	/**
	 *  Starts an export. Returns the job id; the result arrives as an
	 *  `ExportFinished` event.
	 */
	exportBooks: (request: ExportRequestDto) => typedError<string, AppError>(__TAURI_INVOKE("export_books", { request })),
	/**  References for books, ready to paste. */
	copyCitation: (ids: string[], style: CitationStyle) => typedError<Citation, AppError>(__TAURI_INVOKE("copy_citation", { ids, style })),
	/**  What a Libreri archive holds and what importing it would do. */
	inspectArchive: (path: string) => typedError<ArchiveSummaryDto, AppError>(__TAURI_INVOKE("inspect_archive", { path })),
	/**
	 *  Imports a Libreri archive into the open library (owner only). Returns
	 *  the job id; the report arrives as an `ArchiveImported` event.
	 */
	importArchive: (path: string, profiles: ProfileMappingDto[]) => typedError<string, AppError>(__TAURI_INVOKE("import_archive", { path, profiles })),
	/**
	 *  Makes a new library in `folder` (new or empty) and restores a backup or
	 *  export into it, owner included.
	 */
	restoreLibrary: (archive: string, folder: string) => typedError<RestoredLibrary, AppError>(__TAURI_INVOKE("restore_library", { archive, folder })),
	/**  Checks the library for missing files, broken links and other problems. */
	healthCheck: () => typedError<HealthReportDto, AppError>(__TAURI_INVOKE("health_check")),
	/**  Fixes what the health check can fix by itself. Returns how many things. */
	repairHealth: () => typedError<number, AppError>(__TAURI_INVOKE("repair_health")),
	/**  Puts a missing book's file back ("Locate file…"). */
	locateFile: (id: string, path: string, copy: boolean, acceptOther: boolean) => typedError<LocateResult, AppError>(__TAURI_INVOKE("locate_file", { id, path, copy, acceptOther })),
	/**  Backups and the file kept up to date, for Settings › Export & import. */
	getBackupSettings: () => typedError<BackupSettingsDto, AppError>(__TAURI_INVOKE("get_backup_settings")),
	/**  Changes the backup settings (owner only). */
	setBackupSettings: (change: BackupSettingsChange) => typedError<BackupSettingsDto, AppError>(__TAURI_INVOKE("set_backup_settings", { change })),
	/**  Starts a backup now. Returns the job id, or `None` if one is running. */
	backUpNow: () => typedError<string | null, AppError>(__TAURI_INVOKE("back_up_now")),
	/**  Shows a file (an export or a backup) in the system file manager. */
	revealPath: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("reveal_path", { path })),
	/**  Pages of a PDF that say how to measure them (CAD and map exports). */
	measureScales: (id: string) => typedError<PageScaleDto[], AppError>(__TAURI_INVOKE("measure_scales", { id })),
	/**
	 *  Reads a picture file for the markup picture and signature tools, made
	 *  smaller when it is large.
	 */
	readPicture: (path: string) => typedError<PictureDto, AppError>(__TAURI_INVOKE("read_picture", { path })),
	/**
	 *  Saves a copy of the book with its markup drawn in, as a PDF at `dest`.
	 *  With `add_to_library`, the copy is also imported next to the book.
	 */
	exportMarkedUp: (id: string, dest: string, pages: DrawPage[], addToLibrary: boolean) => typedError<null, AppError>(__TAURI_INVOKE("export_marked_up", { id, dest, pages, addToLibrary })),
	/**  Books whose text matches `query` (words, "a phrase", -left-out). */
	searchText: (query: string, limit: number) => typedError<TextMatchDto[], AppError>(__TAURI_INVOKE("search_text", { query, limit })),
	/**  Every match in one book, in reading order. */
	searchInBook: (id: string, query: string, limit: number) => typedError<Hit[], AppError>(__TAURI_INVOKE("search_in_book", { id, query, limit })),
	/**  Whether a book's words can be searched, and its OCR text. */
	textStatus: (id: string) => typedError<TextStatusDto, AppError>(__TAURI_INVOKE("text_status", { id })),
	searchIndexStatus: () => typedError<IndexStatusDto, AppError>(__TAURI_INVOKE("search_index_status")),
	/**  Empties the index and fills it again in the background. */
	rebuildSearchIndex: () => typedError<null, AppError>(__TAURI_INVOKE("rebuild_search_index")),
	/**  Starts indexing now (it also runs after every change to the library). */
	updateSearchIndex: () => typedError<null, AppError>(__TAURI_INVOKE("update_search_index")),
	/**
	 *  Reads scanned PDF and DjVu books with OCR in the background. Returns
	 *  the job id; the result arrives as `OcrFinished`.
	 */
	makeSearchable: (ids: string[], languages: string[], redo: boolean) => typedError<string, AppError>(__TAURI_INVOKE("make_searchable", { ids, languages, redo })),
	/**  Removes a book's OCR text. */
	forgetOcr: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("forget_ocr", { id })),
	/**  Books whose pages are scans without text (all or some). */
	booksWithoutText: () => typedError<UnsearchableDto[], AppError>(__TAURI_INVOKE("books_without_text")),
	/**  Pages of a PDF that have OCR text, for the reader's hidden text layer. */
	ocrPages: (id: string) => typedError<number[], AppError>(__TAURI_INVOKE("ocr_pages", { id })),
	ocrLanguages: () => typedError<OcrLanguagesDto, AppError>(__TAURI_INVOKE("ocr_languages")),
	setOcrLanguages: (languages: string[]) => typedError<null, AppError>(__TAURI_INVOKE("set_ocr_languages", { languages })),
	/**  Downloads an OCR language; progress arrives as `OcrLanguageDownload`. */
	downloadOcrLanguage: (code: string) => typedError<null, AppError>(__TAURI_INVOKE("download_ocr_language", { code })),
	removeOcrLanguage: (code: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_ocr_language", { code })),
	/**
	 *  Opens a comic or DjVu book: page count, sizes and contents. Pages are
	 *  then loaded from `book://localhost/.pages/<id>/<page>?w=<width>`.
	 */
	openPages: (id: string) => typedError<PageBookDto, AppError>(__TAURI_INVOKE("open_pages", { id })),
	/**  The words of a DjVu page with their boxes, for selecting and finding. */
	pageWords: (id: string, page: number) => typedError<WordDto[], AppError>(__TAURI_INVOKE("page_words", { id, page })),
	/**  The plain text of every DjVu page, for Find in book. */
	pageTexts: (id: string) => typedError<string[], AppError>(__TAURI_INVOKE("page_texts", { id })),
	/**  Which helper programs are installed, and how to install the others. */
	helpersStatus: () => typedError<HelpersDto, AppError>(__TAURI_INVOKE("helpers_status")),
	/**
	 *  Installs a helper with the computer's package manager. Progress arrives
	 *  as `HelperInstall` events; the call returns when it is done.
	 */
	installHelper: (helper: Helper) => typedError<HelpersDto, AppError>(__TAURI_INVOKE("install_helper", { helper })),
	/**  Bytes used by the page cache on this computer. */
	pageCacheSize: () => typedError<number | null, AppError>(__TAURI_INVOKE("page_cache_size")),
	/**  Empties the page cache (pages are made again when read). */
	clearPageCache: () => typedError<null, AppError>(__TAURI_INVOKE("clear_page_cache")),
	/**
	 *  Reads a Calibre library, Zotero folder, BibTeX/RIS file or reading log
	 *  and says what importing it would bring in.
	 */
	inspectForeign: (path: string) => typedError<ForeignSummaryDto, AppError>(__TAURI_INVOKE("inspect_foreign", { path })),
	/**
	 *  Imports from another app (files are copied). Returns the job id; the
	 *  report arrives as a `ForeignImported` event.
	 */
	importForeign: (path: string, options: ForeignImportDto) => typedError<string, AppError>(__TAURI_INVOKE("import_foreign", { path, options })),
	/**  Applies page edits to a PDF. The old file is kept as a version. */
	editPages: (id: string, plan: EditPlan) => typedError<EditResultDto, AppError>(__TAURI_INVOKE("edit_pages", { id, plan })),
	/**
	 *  Writes the edited pages as a new book next to this one (the book
	 *  itself is not changed): "Save as new book", extracting and splitting.
	 */
	savePagesAsBook: (id: string, plan: EditPlan, name: string) => typedError<null, AppError>(__TAURI_INVOKE("save_pages_as_book", { id, plan, name })),
	/**
	 *  Saves a PDF with filled-in form fields (base64 from the reader) as the
	 *  book's new version.
	 */
	saveFilledForm: (id: string, data: string) => typedError<BookDto, AppError>(__TAURI_INVOKE("save_filled_form", { id, data })),
	/**
	 *  Writes markup into the PDF as standard annotations (a new version) and
	 *  removes those marks from Libreri's own markup.
	 */
	saveMarkupIntoPdf: (id: string, annots: PdfAnnot[]) => typedError<BookDto, AppError>(__TAURI_INVOKE("save_markup_into_pdf", { id, annots })),
	/**  A book's earlier versions, newest first. */
	listVersions: (id: string) => typedError<VersionDto[], AppError>(__TAURI_INVOKE("list_versions", { id })),
	/**  Makes an earlier version current again (the current file is kept). */
	restoreVersion: (id: string, version: string) => typedError<BookDto, AppError>(__TAURI_INVOKE("restore_version", { id, version })),
	deleteVersion: (id: string, version: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_version", { id, version })),
	/**  Saves a copy of an earlier version where the reader chooses. */
	saveVersionCopy: (id: string, version: string, dest: string) => typedError<null, AppError>(__TAURI_INVOKE("save_version_copy", { id, version, dest })),
	/**  How much room earlier versions take. */
	versionsUsage: () => typedError<VersionsUsage, AppError>(__TAURI_INVOKE("versions_usage")),
	/**  Deletes every earlier version of every book. */
	deleteAllVersions: () => typedError<number, AppError>(__TAURI_INVOKE("delete_all_versions")),
	/**
	 *  Starts the phone page for photos of paper pages; photos arrive as
	 *  `PhonePage` events.
	 */
	startPhonePages: () => typedError<PhonePairingDto, AppError>(__TAURI_INVOKE("start_phone_pages")),
	/**  How many pages a PDF file has (before taking pages from it). */
	pdfPageCount: (path: string) => typedError<number, AppError>(__TAURI_INVOKE("pdf_page_count", { path })),
	/**
	 *  Opens both sides and starts comparing them; the result arrives as a
	 *  `CompareFinished` event (progress as job events).
	 */
	startCompare: (a: CompareSourceDto, b: CompareSourceDto) => typedError<CompareStarted, AppError>(__TAURI_INVOKE("start_compare", { a, b })),
	/**  A comparison's result (or that it is still running). */
	getComparison: (id: string) => typedError<ComparisonDto, AppError>(__TAURI_INVOKE("get_comparison", { id })),
	/**  Saves the comparison as a PDF report at `dest`. */
	exportCompareReport: (id: string, dest: string) => typedError<null, AppError>(__TAURI_INVOKE("export_compare_report", { id, dest })),
	/**  Forgets a comparison (its view closed). */
	closeCompare: (id: string) => __TAURI_INVOKE<void>("close_compare", { id }),
	/**  Length and chapters of an audiobook. */
	audioInfo: (id: string) => typedError<AudioInfoDto, AppError>(__TAURI_INVOKE("audio_info", { id })),
	getAudioLink: (id: string) => typedError<AudioLinkDto, AppError>(__TAURI_INVOKE("get_audio_link", { id })),
	/**  Links an audiobook to its book (or unlinks it with `None`). */
	setAudioLink: (id: string, text: string | null) => typedError<AudioLinkDto, AppError>(__TAURI_INVOKE("set_audio_link", { id, text })),
	setSyncPoints: (id: string, points: SyncPointDto[]) => typedError<AudioLinkDto, AppError>(__TAURI_INVOKE("set_sync_points", { id, points })),
	/**  Audiobooks linked to a book. */
	audiobooksFor: (id: string) => typedError<BookDto[], AppError>(__TAURI_INVOKE("audiobooks_for", { id })),
	/**  eSpeak NG voices (none when it is not installed). */
	systemVoices: () => typedError<Voice[], AppError>(__TAURI_INVOKE("system_voices")),
	/**
	 *  Speaks `text` with eSpeak NG; returns when done (true) or stopped
	 *  (false).
	 */
	systemSpeak: (text: string, voice: string | null, rate: number | null) => typedError<boolean, AppError>(__TAURI_INVOKE("system_speak", { text, voice, rate })),
	systemStopSpeaking: () => __TAURI_INVOKE<void>("system_stop_speaking"),
	speechSettings: () => __TAURI_INVOKE<SpeechSettingsDto>("speech_settings"),
	/**
	 *  Chooses the model (only a downloaded one), the language spoken and
	 *  whether voice notes are written down.
	 */
	setSpeechSettings: (model: string | null, language: string | null, transcribeNotes: boolean) => typedError<SpeechSettingsDto, AppError>(__TAURI_INVOKE("set_speech_settings", { model, language, transcribeNotes })),
	/**
	 *  Downloads a model; progress arrives as `SpeechModelDownload`. The
	 *  first model downloaded becomes the one used.
	 */
	downloadSpeechModel: (id: string) => typedError<SpeechSettingsDto, AppError>(__TAURI_INVOKE("download_speech_model", { id })),
	cancelSpeechModelDownload: (id: string) => __TAURI_INVOKE<void>("cancel_speech_model_download", { id }),
	/**
	 *  Removes a downloaded model. If it was the one used, another downloaded
	 *  model (if any) takes its place.
	 */
	removeSpeechModel: (id: string) => typedError<SpeechSettingsDto, AppError>(__TAURI_INVOKE("remove_speech_model", { id })),
	/**
	 *  Writes down a stretch of speech (dictation). `lang` is a hint (the
	 *  book's language) used when Settings do not name one.
	 */
	transcribePcm: (pcmBase64: string, lang: string | null) => typedError<string, AppError>(__TAURI_INVOKE("transcribe_pcm", { pcmBase64, lang })),
	/**  Saves a recording as FLAC in the profile's voice notes. */
	saveVoiceNote: (pcmBase64: string) => typedError<VoiceNoteDto, AppError>(__TAURI_INVOKE("save_voice_note", { pcmBase64 })),
	/**  Writes down what is said in a saved recording. */
	transcribeVoiceNote: (path: string, lang: string | null) => typedError<string, AppError>(__TAURI_INVOKE("transcribe_voice_note", { path, lang })),
	/**
	 *  Starts finding sync points by listening; ends with `AutoSyncFinished`.
	 *  Returns the job id.
	 */
	autoSyncAudiobook: (id: string) => typedError<string, AppError>(__TAURI_INVOKE("auto_sync_audiobook", { id })),
	/**  Adds a photo (a data: URL, from the camera or the phone). */
	captureAdd: (photo: string) => typedError<CapturePhoto, AppError>(__TAURI_INVOKE("capture_add", { photo })),
	/**  Adds a picture file from the computer. */
	captureAddFile: (path: string) => typedError<CapturePhoto, AppError>(__TAURI_INVOKE("capture_add_file", { path })),
	/**  The page as it will be saved, small (a data: URL). */
	capturePreview: (page: CapturePageSpec) => typedError<string, AppError>(__TAURI_INVOKE("capture_preview", { page })),
	/**
	 *  Saves the pages as one PDF. With `read_text`, Tesseract (when installed)
	 *  reads them first, so the PDF can be searched.
	 */
	captureSave: (pages: CapturePageSpec[], title: string, readText: boolean) => typedError<CaptureSaved, AppError>(__TAURI_INVOKE("capture_save", { pages, title, readText })),
	/**  Forgets photos that were not saved. */
	captureDiscard: (ids: string[]) => __TAURI_INVOKE<void>("capture_discard", { ids }),
	/**  Opens a captured PDF in the system's PDF app. */
	openNoteFile: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("open_note_file", { path })),
	/**  The profile's canvases, newest first (only a book's, when given). */
	canvases: (book: string | null) => typedError<CanvasDto[], AppError>(__TAURI_INVOKE("canvases", { book })),
	/**  Starts a canvas. Returns its path. */
	createCanvas: (title: string, book: string | null, paper: string) => typedError<string, AppError>(__TAURI_INVOKE("create_canvas", { title, book, paper })),
	readCanvas: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("read_canvas", { path })),
	writeCanvas: (path: string, content: string) => typedError<null, AppError>(__TAURI_INVOKE("write_canvas", { path, content })),
	setCanvasPaper: (path: string, paper: string) => typedError<null, AppError>(__TAURI_INVOKE("set_canvas_paper", { path, paper })),
	/**  Renames a canvas; returns its new path. */
	renameCanvas: (path: string, title: string) => typedError<string, AppError>(__TAURI_INVOKE("rename_canvas", { path, title })),
	deleteCanvas: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_canvas", { path })),
	inkSettings: () => __TAURI_INVOKE<InkSettingsDto>("ink_settings"),
	setInkEngine: (engine: string) => typedError<InkSettingsDto, AppError>(__TAURI_INVOKE("set_ink_engine", { engine })),
	/**
	 *  Reads handwriting: a PNG of the ink (base64), with the engine chosen in
	 *  Settings. `lang` is the book's language, when known.
	 */
	inkToText: (pngBase64: string, lang: string | null) => typedError<string, AppError>(__TAURI_INVOKE("ink_to_text", { pngBase64, lang })),
	/**  Extra fonts for canvases, and which are downloaded. */
	canvasFonts: () => __TAURI_INVOKE<ExtraFont[]>("canvas_fonts"),
	/**  Downloads an extra canvas font; progress arrives as `CanvasFontDownload`. */
	downloadCanvasFont: (id: string) => typedError<ExtraFont[], AppError>(__TAURI_INVOKE("download_canvas_font", { id })),
	cancelCanvasFontDownload: (id: string) => __TAURI_INVOKE<void>("cancel_canvas_font_download", { id }),
	removeCanvasFont: (id: string) => typedError<ExtraFont[], AppError>(__TAURI_INVOKE("remove_canvas_font", { id })),
	/**
	 *  Fetches a link's details (once, when it is being added). Nothing is
	 *  saved until [`link_save`].
	 */
	linkFetch: (url: string) => typedError<LinkPreviewDto, AppError>(__TAURI_INVOKE("link_fetch", { url })),
	/**
	 *  Keeps a fetched link's picture and, for a web page when asked, an
	 *  offline copy of it. `url` is the address [`link_fetch`] returned.
	 */
	linkSave: (url: string, title: string, keepCopy: boolean) => typedError<LinkSavedDto, AppError>(__TAURI_INVOKE("link_save", { url, title, keepCopy })),
	/**  A video or audio file chosen to link to. */
	linkFile: (path: string) => typedError<LinkFileDto, AppError>(__TAURI_INVOKE("link_file", { path })),
	/**
	 *  Where a linked video or audio file plays from: a `book://` path
	 *  (`.media/<token>/<name>`), usable while the app runs.
	 */
	linkMediaUrl: (file: string) => typedError<string, AppError>(__TAURI_INVOKE("link_media_url", { file })),
	/**  The player for an embedded video, at a start time (seconds). */
	linkPlayer: (url: string, video: { provider: "youtube"; id: string } | { provider: "vimeo"; id: string; hash: string | null } | null, embed: string | null, start: number | null) => typedError<PlayerDto, AppError>(__TAURI_INVOKE("link_player", { url, video, embed, start })),
	/**  Opens a player in a window of its own. */
	linkPopOut: (page: string, title: string) => typedError<null, AppError>(__TAURI_INVOKE("link_pop_out", { page, title })),
	/**
	 *  Opens a linked file (an offline copy, or a video or recording) in the
	 *  app the system uses for it.
	 */
	linkOpenFile: (file: string) => typedError<null, AppError>(__TAURI_INVOKE("link_open_file", { file })),
	/**  The folders and feeds, with counts. */
	feedsOverview: (space: Space) => typedError<FeedsDto, AppError>(__TAURI_INVOKE("feeds_overview", { space })),
	/**  The items that match, newest first. */
	feedItems: (space: Space, filter: ItemFilter) => typedError<ItemsDto, AppError>(__TAURI_INVOKE("feed_items", { space, filter })),
	/**  Finds the feed for an address (a feed's, or a site's). */
	feedFind: (space: Space, address: string) => typedError<FeedPreviewDto, AppError>(__TAURI_INVOKE("feed_find", { space, address })),
	/**  Follows a feed. Its items are fetched by [`feeds_refresh`]. */
	feedAdd: (space: Space, url: string, title: string, folder: string | null, autoDownload: boolean) => typedError<string, AppError>(__TAURI_INVOKE("feed_add", { space, url, title, folder, autoDownload })),
	arxivCategories: () => __TAURI_INVOKE<ArxivGroup[]>("arxiv_categories"),
	suggestedFeeds: () => __TAURI_INVOKE<Suggested[]>("suggested_feeds"),
	/**
	 *  Follows arXiv categories (each in "arXiv › <group>") and, optionally,
	 *  a search. Returns the new feeds' ids.
	 */
	feedsAddArxiv: (codes: string[], search: string | null, autoDownload: boolean) => typedError<string[], AppError>(__TAURI_INVOKE("feeds_add_arxiv", { codes, search, autoDownload })),
	feedChange: (space: Space, id: string, changeTo: FeedChange) => typedError<null, AppError>(__TAURI_INVOKE("feed_change", { space, id, changeTo })),
	/**  Stops following a feed. Downloads stay. */
	feedRemove: (space: Space, id: string) => typedError<null, AppError>(__TAURI_INVOKE("feed_remove", { space, id })),
	feedFolderAdd: (space: Space, name: string, parent: string | null) => typedError<string, AppError>(__TAURI_INVOKE("feed_folder_add", { space, name, parent })),
	feedFolderChange: (space: Space, id: string, changeTo: FolderChange) => typedError<null, AppError>(__TAURI_INVOKE("feed_folder_change", { space, id, changeTo })),
	/**  Removes a folder; its feeds and folders move up a level. */
	feedFolderRemove: (space: Space, id: string) => typedError<null, AppError>(__TAURI_INVOKE("feed_folder_remove", { space, id })),
	feedsSettingsSet: (space: Space, settings: FeedSettings) => typedError<null, AppError>(__TAURI_INVOKE("feeds_settings_set", { space, settings })),
	/**
	 *  Looks for new items in every feed (or those given), then downloads the
	 *  new items of feeds set to download by themselves.
	 */
	feedsRefresh: (space: Space, ids: string[] | null) => typedError<RefreshReport, AppError>(__TAURI_INVOKE("feeds_refresh", { space, ids })),
	feedItemDownload: (space: Space, id: string) => typedError<FeedItem, AppError>(__TAURI_INVOKE("feed_item_download", { space, id })),
	/**  Deletes items (and their downloads). They do not come back. */
	feedItemsDelete: (space: Space, ids: string[]) => typedError<null, AppError>(__TAURI_INVOKE("feed_items_delete", { space, ids })),
	/**  Deletes an item's download only (the item stays, to download again). */
	feedItemForgetFile: (space: Space, id: string) => typedError<null, AppError>(__TAURI_INVOKE("feed_item_forget_file", { space, id })),
	feedItemsRead: (space: Space, ids: string[], readNow: boolean) => typedError<null, AppError>(__TAURI_INVOKE("feed_items_read", { space, ids, readNow })),
	/**  Marks everything shown by a folder or feed (or all) as read. */
	feedAllRead: (space: Space, folder: string | null, feed: string | null) => typedError<null, AppError>(__TAURI_INVOKE("feed_all_read", { space, folder, feed })),
	/**
	 *  Adds an item to the library, in `folder` (relative to `Books/`),
	 *  downloading it first if need be. Returns the book's id.
	 */
	feedItemToLibrary: (space: Space, id: string, folder: string) => typedError<string, AppError>(__TAURI_INVOKE("feed_item_to_library", { space, id, folder })),
	/**  Adds the feeds of an OPML file (in `parent`, or at the top level). */
	feedsImportOpml: (space: Space, path: string, parent: string | null) => typedError<[number, number], AppError>(__TAURI_INVOKE("feeds_import_opml", { space, path, parent })),
	/**  Writes the folders and feeds to an OPML file. */
	feedsExportOpml: (space: Space, path: string) => typedError<null, AppError>(__TAURI_INVOKE("feeds_export_opml", { space, path })),
	/**  Shows the feeds folder, or a download, in the file manager. */
	feedsReveal: (file: string | null) => typedError<null, AppError>(__TAURI_INVOKE("feeds_reveal", { file })),
	/**  Opens a download in the app the system uses for it. */
	feedOpenFile: (file: string) => typedError<null, AppError>(__TAURI_INVOKE("feed_open_file", { file })),
	/**  Whether a Podcast Index key is set on this computer. */
	podcastIndexStatus: () => __TAURI_INVOKE<PodcastIndexDto>("podcast_index_status"),
	/**
	 *  Saves (after checking it) or removes (empty key) a Podcast Index key
	 *  and secret. Kept on this computer only, never exported.
	 */
	podcastIndexSet: (key: string, secret: string) => typedError<PodcastIndexDto, AppError>(__TAURI_INVOKE("podcast_index_set", { key, secret })),
	/**
	 *  Shows matching the words: Apple's podcast search, or Podcast Index
	 *  (`index`) when a key is set.
	 */
	podcastSearch: (query: string, index: boolean) => typedError<Show[], AppError>(__TAURI_INVOKE("podcast_search", { query, index })),
	/**  Popular shows on Podcast Index (needs a key), optionally in a category. */
	podcastTrending: (category: string | null) => typedError<Show[], AppError>(__TAURI_INVOKE("podcast_trending", { category })),
	podcastCategories: () => typedError<string[], AppError>(__TAURI_INVOKE("podcast_categories")),
	/**  Keeps where listening stopped, and whether the episode was finished. */
	podcastProgress: (id: string, position: number | null, duration: number | null, played: boolean) => typedError<null, AppError>(__TAURI_INVOKE("podcast_progress", { id, position, duration, played })),
	/**  Marks episodes played (or not), keeping no position. */
	podcastPlayed: (ids: string[], played: boolean) => typedError<null, AppError>(__TAURI_INVOKE("podcast_played", { ids, played })),
	/**  Sets the Up next queue (episode ids, in order). */
	podcastQueueSet: (ids: string[]) => typedError<null, AppError>(__TAURI_INVOKE("podcast_queue_set", { ids })),
	/**  Episodes by id (for the queue and the player). */
	podcastEpisodes: (ids: string[]) => typedError<FeedItem[], AppError>(__TAURI_INVOKE("podcast_episodes", { ids })),
	/**  An episode's transcript, from the show (none when it has none). */
	podcastTranscript: (id: string) => typedError<Cue[], AppError>(__TAURI_INVOKE("podcast_transcript", { id })),
	/**  An episode's chapters, from the show (none when it has none). */
	podcastChapters: (id: string) => typedError<Chapter[], AppError>(__TAURI_INVOKE("podcast_chapters", { id })),
	mathsSettings: () => __TAURI_INVOKE<MathsSettingsDto>("maths_settings"),
	/**
	 *  Turns reading maths from pictures on or off (the model stays until
	 *  removed).
	 */
	setMathsFromPictures: (on: boolean) => typedError<MathsSettingsDto, AppError>(__TAURI_INVOKE("set_maths_from_pictures", { on })),
	/**  Downloads the model; progress arrives as `MathsDownload`. */
	downloadMathsModel: () => typedError<MathsSettingsDto, AppError>(__TAURI_INVOKE("download_maths_model")),
	cancelMathsDownload: () => __TAURI_INVOKE<void>("cancel_maths_download"),
	/**  Removes the model and turns the feature off. */
	removeMathsModel: () => typedError<MathsSettingsDto, AppError>(__TAURI_INVOKE("remove_maths_model")),
	/**  Reads a picture of maths (PNG or JPEG, base64 or a data URL) as LaTeX. */
	mathsFromPicture: (picture: string) => typedError<string, AppError>(__TAURI_INVOKE("maths_from_picture", { picture })),
	spellDictionaries: () => __TAURI_INVOKE<DictionaryInfo[]>("spell_dictionaries"),
	/**  Downloads a dictionary; progress arrives as `DictionaryDownload`. */
	downloadDictionary: (code: string) => typedError<DictionaryInfo[], AppError>(__TAURI_INVOKE("download_dictionary", { code })),
	cancelDictionaryDownload: (code: string) => __TAURI_INVOKE<void>("cancel_dictionary_download", { code }),
	removeDictionary: (code: string) => typedError<DictionaryInfo[], AppError>(__TAURI_INVOKE("remove_dictionary", { code })),
	/**
	 *  The words of `text` that look misspelt, in the chosen languages. The
	 *  open book's names and terms (`book`) are accepted once they are learned.
	 */
	spellCheck: (text: string, languages: string[], book: string | null) => typedError<Miss[], AppError>(__TAURI_INVOKE("spell_check", { text, languages, book })),
	/**  Corrections for a word. */
	spellSuggest: (word: string, languages: string[], book: string | null) => typedError<string[], AppError>(__TAURI_INVOKE("spell_suggest", { word, languages, book })),
	/**
	 *  Ways to finish a word being typed: the person's own words, then the
	 *  open book's, their notes' and the dictionaries'.
	 */
	spellComplete: (prefix: string, languages: string[], book: string | null) => typedError<string[], AppError>(__TAURI_INVOKE("spell_complete", { prefix, languages, book })),
	/**
	 *  Starts learning a book's words (when it opens), so checking and
	 *  completing know its names and terms.
	 */
	spellLearnBook: (book: string) => __TAURI_INVOKE<void>("spell_learn_book", { book }),
	ownWords: () => typedError<string[], AppError>(__TAURI_INVOKE("own_words")),
	addOwnWord: (word: string) => typedError<string[], AppError>(__TAURI_INVOKE("add_own_word", { word })),
	removeOwnWord: (word: string) => typedError<string[], AppError>(__TAURI_INVOKE("remove_own_word", { word })),
};

/** Events */
export const events = {
	archiveImported: makeEvent<ArchiveImported>("archive-imported"),
	autoSyncFinished: makeEvent<AutoSyncFinished>("auto-sync-finished"),
	backupFinished: makeEvent<BackupFinished>("backup-finished"),
	canvasFontDownload: makeEvent<CanvasFontDownload>("canvas-font-download"),
	compareFinished: makeEvent<CompareFinished>("compare-finished"),
	detailsFilled: makeEvent<DetailsFilled>("details-filled"),
	dictionaryDownload: makeEvent<DictionaryDownload>("dictionary-download"),
	exportFinished: makeEvent<ExportFinished>("export-finished"),
	feedsChanged: makeEvent<FeedsChanged>("feeds-changed"),
	foreignImported: makeEvent<ForeignImported>("foreign-imported"),
	helperInstall: makeEvent<HelperInstall>("helper-install"),
	importFinished: makeEvent<ImportFinished>("import-finished"),
	jobEventPayload: makeEvent<JobEventPayload>("job-event-payload"),
	libraryChanged: makeEvent<LibraryChanged>("library-changed"),
	mathsDownload: makeEvent<MathsDownload>("maths-download"),
	ocrFinished: makeEvent<OcrFinished>("ocr-finished"),
	ocrLanguageDownload: makeEvent<OcrLanguageDownload>("ocr-language-download"),
	phonePage: makeEvent<PhonePage>("phone-page"),
	phoneScan: makeEvent<PhoneScan>("phone-scan"),
	searchIndexProgress: makeEvent<SearchIndexProgress>("search-index-progress"),
	sessionChanged: makeEvent<SessionChanged>("session-changed"),
	speechModelDownload: makeEvent<SpeechModelDownload>("speech-model-download"),
};

/* Types */
export type Annotation = {
	/**  UUID, created by whoever makes the annotation. */
	id: string,
	bookId: BookId,
	kind: AnnotationKind,
	color: HighlightColor | null,
	/**  Format-specific position as JSON, e.g. `{"type":"pdf","page":4,…}`. */
	locator: string,
	quote: TextQuote | null,
	/**  The comment written on a highlight, or a bookmark's name. */
	note: string | null,
	/**  Where it is, for people: "p. 4" or a chapter title. */
	label: string | null,
	/**  0.0–1.0 through the book, for sorting. */
	position: number | null,
	createdAt: string,
	modifiedAt: string,
};

export type AnnotationKind = "highlight" | "bookmark" | 
/**
 *  A drawing, shape, text box, sticky note, stamp, image or measurement
 *  on a page (markup mode). The locator holds the whole item.
 */
"markup" | 
/**
 *  A spoken note: on selected text (with a quote) or at a place. The
 *  locator's `audio` is the recording in the profile's notes folder;
 *  `note` holds its transcript.
 */
"voice" | 
/**
 *  Photographed paper notes about a place: the locator's `capture` is
 *  the PDF in the profile's notes folder; `note` holds its text.
 */
"capture" | 
/**
 *  A link to a web page, a video, a file on this computer or another
 *  book, from selected text or a place: the locator's `link` holds it.
 */
"link";

export type AppError = {
	kind: AppErrorKind,
	message: string,
};

export type AppErrorKind = "notALibrary" | "alreadyALibrary" | "folderNotEmpty" | "formatTooNew" | "lockedElsewhere" | "alreadyOpenHere" | "storage" | "io" | 
/**  No library is open (the window is on the Welcome screen). */
"noLibrary" | "notFound" | 
/**  Something the user typed was refused; the message says why. */
"invalidInput" | "nameTaken" | "trash" | "cancelled" | 
/**  Nobody is signed in: show the profile picker. */
"signedOut" | 
/**  The PIN was wrong; the message says how many tries are left. */
"wrongPin" | 
/**  Too many wrong PINs; the message says how long to wait. */
"pinLocked" | 
/**  The signed-in profile may not do this (Kids, Guest, not the owner). */
"notAllowed";

export type AppInfo = {
	version: string,
	platform: string,
};

export type AppliedDetails = {
	book: BookDto,
	/**  Why the picked cover could not be used, if it could not. */
	coverError: string | null,
};

/**  A Libreri archive was imported: the summary shown to the user. */
export type ArchiveImported = {
	jobId: string,
	linked: number,
	added: number,
	otherFile: number,
	missing: number,
	filesRestored: number,
	detailsUpdated: number,
	notesAdded: number,
	notesUpdated: number,
	notesKept: number,
	noteFilesAdded: number,
	noteConflicts: string[],
	profilesCreated: string[],
	missingBooks: string[],
	warnings: string[],
};

export type ArchiveKind = 
/**  Made with Export; never carries PINs. */
"export" | 
/**  Made by a backup; carries PINs so a restore brings them back. */
"backup";

export type ArchiveProfileDto = {
	archiveId: string,
	name: string,
	kind: ProfileKind,
	suggestion: ProfileTargetDto,
};

export type ArchiveSummaryDto = {
	kind: ArchiveKind,
	createdAt: string,
	createdBy: string,
	libraryName: string,
	includesBookFiles: boolean,
	includesPins: boolean,
	books: number,
	notes: number,
	notebooks: number,
	linked: number,
	withFile: number,
	otherFile: number,
	missing: number,
	profiles: ArchiveProfileDto[],
};

export type ArxivCategory = {
	/**  "cs.AI" */
	code: string,
	/**  "Artificial Intelligence" */
	name: string,
};

/**  A group of arXiv categories ("Computer Science"). */
export type ArxivGroup = {
	name: string,
	categories: ArxivCategory[],
};

export type AudioInfoDto = {
	duration: number | null,
	chapters: ChapterDto[],
};

export type AudioLinkDto = {
	/**  The book the audiobook reads. */
	text: BookDto | null,
	points: SyncPointDto[],
};

/**  A file (BibTeX, CSL-JSON…) Libreri rewrites whenever the library changes. */
export type AutoExport = {
	format: ExportFormat,
	path: string,
};

/**  Finding sync points by listening finished. */
export type AutoSyncFinished = {
	audioId: string,
	/**  Sync points found (0 when none could be placed). */
	found: number,
	/**  Stretches listened to. */
	tried: number,
	error: string | null,
};

export type BackupFileDto = {
	path: string,
	createdAt: string,
	size: number,
	includesBookFiles: boolean,
	books: number,
};

/**  A backup finished (by hand or on schedule). */
export type BackupFinished = {
	jobId: string,
	/**  Set when the backup was written. */
	path: string | null,
	error: string | null,
	/**  Started by the schedule rather than "Back up now". */
	scheduled: boolean,
};

export type BackupSettingsChange = {
	enabled: boolean,
	folder: string | null,
	everyHours: number,
	keep: number,
	bookFiles: boolean,
	autoExport: AutoExport | null,
};

export type BackupSettingsDto = {
	enabled: boolean,
	folder: string | null,
	everyHours: number,
	keep: number,
	bookFiles: boolean,
	lastBackup: string | null,
	lastError: string | null,
	lastAttempt: string | null,
	autoExport: AutoExport | null,
	lastAutoExport: string | null,
	autoExportError: string | null,
	/**  This library's backups in the folder, newest first. */
	backups: BackupFileDto[],
	/**  The signed-in profile may change these settings (the owner). */
	canEdit: boolean,
};

/**  Everything about one book in the library. */
export type Book = {
	id: BookId,
	/**  Relative to the library root, with `/` separators: "Books/Physics/a.pdf". */
	relPath: string,
	fileType: FileType,
	/**  Sent to TypeScript as a number; no file comes near 2^53 bytes. */
	fileSize: number,
	hasCover: boolean,
	/**  The file could not be found at `rel_path` during the last scan. */
	missing: boolean,
	addedAt: string,
	modifiedAt: string,
	metadata: BookMetadata,
	user: BookUserState,
};

/**
 *  A book as the interface sees it: the stored record plus the paths of
 *  its images (served by `book://`) and its folder.
 */
export type BookDto = {
	/**  Folder relative to `Books/` ("" = top level). */
	folder: string,
	thumbnail: string | null,
	cover: string | null,
} & Book;

/**  Identifier of a book: the lowercase hex BLAKE3 hash of the file content. */
export type BookId = string;

/**
 *  Bibliographic details shared by every profile. This is what the details
 *  panel edits and what the JSON sidecar stores.
 */
export type BookMetadata = {
	title?: string,
	subtitle?: string | null,
	authors?: string[],
	/**  Editors, translators, illustrators — free text such as "Jane Smith (translator)". */
	contributors?: string[],
	about?: string | null,
	tags?: string[],
	/**  Hierarchical, written as paths: "Science/Physics". */
	categories?: string[],
	year?: number | null,
	publisher?: string | null,
	pages?: number | null,
	isbn13?: string | null,
	isbn10?: string | null,
	edition?: string | null,
	/**  BCP 47 code such as "en" or "de". */
	language?: string | null,
	contentType?: ContentType,
	series?: string | null,
	seriesNumber?: number | null,
	doi?: string | null,
	arxivId?: string | null,
	journal?: string | null,
	volume?: string | null,
	issue?: string | null,
	url?: string | null,
};

/**  A filter for the book list. Empty lists mean "any". */
export type BookQuery = {
	/**  Folder relative to `Books/` ("" = top level). `None` = whole library. */
	folder?: string | null,
	/**  With `folder`, also include books in its subfolders. */
	includeSubfolders?: boolean,
	/**  Free text matched against title, authors, tags, ISBN, … */
	search?: string | null,
	fileTypes?: FileType[],
	contentTypes?: ContentType[],
	/**  Books must have every one of these tags. */
	tags?: string[],
	/**  Books must be in this category or one below it. */
	category?: string | null,
	status?: ReadingStatus | null,
	favoritesOnly?: boolean,
	/**  `Some(true)` only audiobooks, `Some(false)` hides them. */
	audio?: boolean | null,
	missingOnly?: boolean,
	sort?: SortKey,
	descending?: boolean,
};

export type BookRef = {
	id: string,
	title: string,
	relPath: string,
};

/**  Personal state of one profile for one book. */
export type BookUserState = {
	status?: ReadingStatus,
	/**  0 = not rated, 1–5 stars. */
	rating?: number,
	favorite?: boolean,
	/**  0.0–1.0. */
	progress?: number | null,
	lastOpened?: string | null,
};

export type BrokenLinkDto = {
	note: string,
	line: number,
	link: string,
};

/**
 *  Changes applied to many books at once. `None` leaves a field alone;
 *  `Some("")` clears a text field.
 */
export type BulkEdit = {
	/**  Replaces the authors (an empty list removes them). */
	authors?: string[] | null,
	publisher?: string | null,
	/**  A year, or "" to clear. */
	year?: string | null,
	language?: string | null,
	contentType?: ContentType | null,
	series?: string | null,
	/**  Number the books 1, 2, 3… in the order given. */
	numberSeries?: boolean,
	addTags?: string[],
	removeTags?: string[],
	addCategories?: string[],
	removeCategories?: string[],
};

/**  One source's idea of what the book is. */
export type Candidate = {
	source: Source,
	/**  The source's own id ("OL7353617M", "10.1038/nature14539"). */
	sourceId: string,
	/**  The page about it on the source's website. */
	link: string | null,
	metadata: BookMetadata,
	coverUrl: string | null,
	/**  How well it matches the query, 0–1. An identifier match is 1. */
	score: number | null,
};

export type CanvasDto = {
	title: string,
	relPath: string,
	bookId: string | null,
	paper: string,
	modified: number | null,
	elements: number,
};

/**  Progress of downloading an extra canvas font. */
export type CanvasFontDownload = {
	id: string,
	done: number | null,
	total: number | null,
	finished: boolean,
	error: string | null,
};

/**  How one page should come out. */
export type CapturePageSpec = {
	id: string,
	corners: ([(number | null), (number | null)])[],
	clean: Clean,
	/**  Quarter turns, clockwise. */
	turns: number,
};

export type CapturePhoto = {
	/**  The photo, kept for this capture only. */
	id: string,
	width: number,
	height: number,
	/**
	 *  Where the page was found (top-left, top-right, bottom-right,
	 *  bottom-left), as fractions.
	 */
	corners: ([(number | null), (number | null)])[],
	/**  A small copy to show, as a data: URL. */
	preview: string,
};

export type CaptureSaved = {
	/**  The PDF in the library: `Notes/<profile>/Captures/….pdf`. */
	path: string,
	pages: number,
	/**  The text read from the pages (empty when not read). */
	text: string,
};

/**  One difference. `pair` is the index into the page pairs. */
export type Change = {
	kind: ChangeKind,
	pair: number,
	aRects: ([(number | null), (number | null), (number | null), (number | null)])[],
	bRects: ([(number | null), (number | null), (number | null), (number | null)])[],
	aText: string,
	bText: string,
};

export type ChangeKind = 
/**  Words only in the first document. */
"removed" | 
/**  Words only in the second. */
"added" | 
/**  Words replaced by others. */
"changed" | 
/**  Drawings or pictures look different. */
"look" | "pageRemoved" | "pageAdded";

/**  A chapter of an episode. */
export type Chapter = {
	start: number | null,
	title: string,
};

export type ChapterDto = {
	title: string,
	start: number | null,
};

/**  A formatted reference as plain text and as HTML (with italics). */
export type Citation = {
	text: string,
	html: string,
};

/**  Reference styles offered by "Copy citation". */
export type CitationStyle = "apa" | "mla" | "chicago" | "harvard" | "ieee" | 
/**  A BibTeX entry, for pasting into a `.bib` file. */
"bibtex";

/**  How a page is cleaned. */
export type Clean = 
/**  Colours kept, shadows and a grey cast removed. */
"colour" | 
/**  Grey, with even lighting. */
"grey" | 
/**  Black ink on white paper. */
"blackWhite" | 
/**  Left as photographed. */
"none";

export type CollectionDto = {
	id: string,
	name: string,
	query: BookQuery,
};

/**  A comparison finished (or failed: `error`). */
export type CompareFinished = {
	id: string,
	error: string | null,
};

/**  One side of a comparison. */
export type CompareSourceDto = 
/**  A book as it is now. */
{ kind: "book"; id: string } | 
/**  An earlier version of a book. */
{ kind: "version"; book: string; version: string } | 
/**  A PDF or DjVu file on this computer. */
{ kind: "file"; path: string };

export type CompareStarted = {
	id: string,
	jobId: string,
	aLabel: string,
	bLabel: string,
	aPages: number,
	bPages: number,
};

export type ComparisonDto = {
	aLabel: string,
	bLabel: string,
	aPages: number,
	bPages: number,
	/**  False while it is still running. */
	done: boolean,
	error: string | null,
	pairs: PagePair[],
	changes: Change[],
};

/**  What kind of document a book is. Chosen by the user; guessed on import. */
export type ContentType = "book" | "textbook" | "researchPaper" | "conferencePaper" | "preprint" | "thesis" | "lectureNotes" | "slides" | "technicalReport" | "whitePaper" | "manual" | "reference" | "standard" | "magazine" | "article" | "comic" | "cheatSheet" | "personalNotes" | "audiobook" | "other";

/**
 *  A small text correction: the old words under `rect` are removed and
 *  covered, and `text` is written in their place.
 */
export type Correction = {
	page: number,
	rect: [(number | null), (number | null), (number | null), (number | null)],
	text: string,
	/**  Font size as a fraction of the page width. */
	size: number | null,
	color: string,
	/**  The paper colour around the old words. */
	background: string,
	/**  "sans", "serif" or "mono". */
	font: string,
	/**
	 *  The text drawn as a picture, used when it has characters the
	 *  standard PDF fonts cannot show.
	 */
	picture?: string | null,
};

export type CountDto<T> = {
	value: T,
	count: number,
};

export type CountedBook = {
	book: BookRef,
	notes: number,
};

/**  A line of a transcript. */
export type Cue = {
	/**  Seconds from the start (none: the transcript has no times). */
	start: number | null,
	end: number | null,
	speaker: string | null,
	text: string,
};

/**  "Fill in missing details" finished (by hand, or after an import). */
export type DetailsFilled = {
	jobId: string,
	filled: string[],
	/**  Books with no sure match, to look up one by one. */
	unsure: string[],
	unchanged: number,
	failed: FailedFileDto[],
};

/**  Progress of downloading a spelling dictionary. */
export type DictionaryDownload = {
	code: string,
	done: number | null,
	total: number | null,
	finished: boolean,
	error: string | null,
};

/**  A dictionary Libreri offers. */
export type DictionaryInfo = {
	/**  "en-US", "fr", "hi-IN". */
	code: string,
	name: string,
	/**  About how big the download is, in KB. */
	sizeKb: number,
	builtIn: boolean,
	downloaded: boolean,
};

/**
 *  One thing to draw. Paths use SVG path data (absolute M, L, Q, C, Z) in
 *  fractions of the page as shown (top-left origin); widths and dashes are
 *  fractions of the page width.
 */
export type DrawOp = { type: "fill"; d: string; color: string; opacity: number | null; 
/**  Mixes like a highlighter (darkens, never covers). */
multiply?: boolean } | { type: "stroke"; d: string; color: string; opacity: number | null; width: number | null; dash?: (number | null)[] } | 
/**
 *  A picture (PNG or JPEG data URL): text boxes, stamps, notes and
 *  signatures are sent as pictures so every font and script survives.
 */
{ type: "image"; rect: [(number | null), (number | null), (number | null), (number | null)]; src: string };

/**  What to draw on one page (1-based). */
export type DrawPage = {
	page: number,
	ops: DrawOp[],
};

export type DuplicateDto = {
	file: string,
	existingTitle: string,
	existingId: string,
};

export type DuplicateGroup = {
	key: string,
	books: BookRef[],
};

/**  Everything to do to a PDF. */
export type EditPlan = {
	pages: OutPage[],
	/**  Other PDFs that pages come from (absolute paths, set by the app). */
	files?: string[],
	redactions?: Redaction[],
	corrections?: Correction[],
	compress?: Quality | null,
	/**  Write saved OCR text into the PDF as an invisible text layer. */
	embedOcr?: boolean,
};

export type EditResultDto = {
	book: BookDto,
	pages: number,
	/**  Pages turned into pictures so nothing stayed under a redaction. */
	flattened: number[],
	warnings: string[],
};

/**  An export finished. */
export type ExportFinished = {
	jobId: string,
	path: string,
	books: number,
	notes: number,
	files: number,
	bytes: number,
	warnings: string[],
};

/**  Every format Libreri exports to. */
export type ExportFormat = 
/**  `.libreri` archive: everything, to import into Libreri again. */
"archive" | "csv" | "xlsx" | "json" | "bibtex" | "ris" | "cslJson" | 
/**  A folder of Markdown notes for Obsidian (or any Markdown app). */
"obsidian" | 
/**  Book folders with `metadata.opf` and `cover.jpg`, for Calibre. */
"calibre" | 
/**  A copy of the catalogue database. */
"sqlite";

/**  What the export dialog asks for (board 24). */
export type ExportRequestDto = {
	format: ExportFormat,
	/**  `None` = every book. */
	bookIds: string[] | null,
	dest: string,
	personal: boolean,
	notes: boolean,
	bookFiles: boolean,
	everyone: boolean,
};

/**  A font that can be added. */
export type ExtraFont = {
	id: string,
	name: string,
	description: string,
	sizeMb: number,
	downloaded: boolean,
};

/**  Counts for the sidebar and the filter menus. */
export type FacetsDto = {
	total: number,
	wantToRead: number,
	reading: number,
	finished: number,
	favorites: number,
	audio: number,
	missing: number,
	fileTypes: CountDto<FileType>[],
	contentTypes: CountDto<ContentType>[],
	tags: CountDto<string>[],
	categories: CountDto<string>[],
};

export type FailedFileDto = {
	file: string,
	reason: string,
};

export type FeedChange = {
	title: string | null,
	/**  Move to this folder ("" = the top level). */
	folder: string | null,
	autoDownload: boolean | null,
	/**  Podcasts: play at this speed (0: the usual speed). */
	speed: number | null,
};

export type FeedDto = {
	id: string,
	url: string,
	title: string,
	site: string | null,
	folder: string | null,
	autoDownload: boolean,
	/**  Downloaded by itself because a folder it is in says so. */
	autoFromFolder: boolean,
	checkedAt: string | null,
	error: string | null,
	unread: number,
	total: number,
	/**  Podcasts: who makes it, its artwork (a data URL) and its speed. */
	author: string | null,
	artwork: string | null,
	speed: number | null,
};

/**  One entry of a feed. */
export type FeedEntry = {
	/**  Stays the same for this entry each time the feed is read. */
	key: string,
	title: string,
	/**  The entry's page. */
	link: string | null,
	authors: string[],
	/**  The abstract or summary, as plain text. */
	summary: string,
	/**  When it was published (RFC 3339). */
	published: string | null,
	/**  Topics given by the feed (arXiv: "cs.AI", "math.PR"). */
	topics: string[],
	/**  A PDF of it, when there is one. */
	pdf: string | null,
	doi: string | null,
	arxivId: string | null,
	/**  arXiv: "new", "cross", "replace" or "replace-cross". */
	announce: string | null,
	/**  Podcasts: the episode's audio, its type and length (seconds). */
	audio?: string | null,
	audioType?: string | null,
	duration?: number | null,
	/**  The episode's own picture. */
	image?: string | null,
	/**  Podcasting 2.0: a transcript (address and type) and chapters. */
	transcript?: string | null,
	transcriptType?: string | null,
	chapters?: string | null,
};

export type FeedFolder = {
	id: string,
	name: string,
	/**  The folder it is in (none: top level). */
	parent: string | null,
	/**  Download new items of every feed in it (and its subfolders). */
	autoDownload?: boolean,
};

export type FeedItem = {
	id: string,
	feed: string,
	/**  The feed's title when it came in (kept if the feed is removed). */
	source: string,
	/**  When it came in (RFC 3339). */
	foundAt: string,
	read?: boolean,
	/**  The downloaded file (library-relative, under `Feeds/`). */
	file: string | null,
	/**  The book it became when added to the library. */
	book: string | null,
	downloadError: string | null,
	/**
	 *  Podcasts: where listening stopped (seconds), and whether it was
	 *  heard to the end.
	 */
	position?: number | null,
	played?: boolean,
} & FeedEntry;

export type FeedPreviewDto = {
	/**  The feed's own address (found from a site's address if need be). */
	url: string,
	title: string,
	site: string | null,
	count: number,
	/**  The newest few titles. */
	sample: string[],
	/**  Already followed, under this title. */
	followed: string | null,
};

export type FeedSettings = {
	/**
	 *  Check for new items every this many minutes while Libreri is open
	 *  (0: only when asked).
	 */
	refreshMinutes?: number,
	/**  Items not downloaded are removed after this many days. */
	keepDays?: number,
};

/**
 *  Feeds changed: new items came in, a download started or finished, or
 *  subscriptions were edited. The interface refetches its lists.
 */
export type FeedsChanged = {
	newItems: number,
};

export type FeedsDto = {
	folders: FeedFolder[],
	feeds: FeedDto[],
	settings: FeedSettings,
	unread: number,
	total: number,
	downloaded: number,
	refreshing: boolean,
	/**  Items being downloaded now. */
	downloading: string[],
	/**  Podcasts: episodes to play next, in order. */
	queue: string[],
	/**  Podcasts: episodes started and not finished. */
	inProgress: number,
};

/**  Every file format Libreri accepts, detected from the file extension. */
export type FileType = "pdf" | "epub" | "mobi" | "azw3" | "fb2" | "txt" | "md" | "djvu" | "cbz" | "cbr" | "cb7" | "cba" | "cbt" | "mp3" | "m4b" | "m4a" | "aac" | "ogg" | "opus" | "flac";

export type FolderChange = {
	name: string | null,
	/**  Move into this folder ("" = the top level). */
	parent: string | null,
	autoDownload: boolean | null,
};

export type FolderDto = {
	name: string,
	/**  Relative to `Books/`, `/`-separated. */
	path: string,
	bookCount: number,
	totalCount: number,
	children: FolderDto[],
};

/**
 *  What a folder the user picked contains, so the Welcome screen can offer
 *  the right action.
 */
export type FolderKind = "missing" | "empty" | "library" | "otherFiles";

export type ForeignImportDto = {
	/**  Preferred formats, best first; empty = Libreri's order. */
	formats: FileType[],
	/**  Folder under Books/ ("" = top level). */
	folder: string,
	replacePersonal: boolean,
};

/**  An import from another app finished. */
export type ForeignImported = {
	jobId: string,
	source: string,
	added: number,
	alreadyHere: number,
	detailsAdded: number,
	withoutFile: string[],
	withoutFileCount: number,
	highlightsAdded: number,
	notesAdded: number,
	personalUpdated: number,
	unmatched: string[],
	unmatchedCount: number,
	failed: FailedFileDto[],
	warnings: string[],
};

/**  Where a library comes from. */
export type ForeignSource = 
/**  A Calibre library folder (with `metadata.db`). */
"calibre" | 
/**  Zotero's data folder (with `zotero.sqlite` and `storage/`). */
"zotero" | 
/**  A BibTeX file, such as a Mendeley or JabRef export. */
"bibtex" | 
/**  A RIS file (Mendeley, EndNote, Zotero). */
"ris" | 
/**  Goodreads "Export library" CSV. */
"goodreads" | 
/**  The StoryGraph export CSV. */
"storyGraph";

/**  What a library from another app holds. */
export type ForeignSummaryDto = {
	source: ForeignSource,
	label: string,
	books: number,
	withFiles: number,
	highlights: number,
	notes: number,
	rated: number,
	formats: FormatCount[],
	/**  Goodreads and StoryGraph: books found in this library. */
	matched: number,
	readingLog: boolean,
	warnings: string[],
};

export type FormatCount = {
	fileType: FileType,
	count: number,
};

export type HealthReportDto = {
	checkedAt: string,
	books: number,
	missingFiles: BookRef[],
	otherFileNotes: CountedBook[],
	duplicates: DuplicateGroup[],
	brokenLinks: BrokenLinkDto[],
	missingSidecars: number,
	staleNotebooks: number,
	unusedCovers: number,
	unusedCoverBytes: number,
	unusedVersions: number,
	unusedVersionBytes: number,
	unreadableBackups: string[],
	database: string[],
	fixable: boolean,
};

/**  A helper program (or a set of programs from one package). */
export type Helper = "djvulibre" | "tesseract" | "unar" | "espeak";

export type HelperInfo = {
	name: string,
	purpose: string,
	licence: string,
	/**  How Libreri would install it here, if it can. */
	plan: InstallPlan | null,
} & HelperStatus;

/**  Progress of installing a helper program. */
export type HelperInstall = {
	helper: Helper,
	/**  A line of the package manager's output. */
	line: string | null,
	done: boolean,
	error: string | null,
};

/**  Is a helper there, and which version. */
export type HelperStatus = {
	helper: Helper,
	installed: boolean,
	/**  Where the main program is. */
	path: string | null,
	version: string | null,
	/**  Programs that are missing. */
	missing: string[],
};

export type HelpersDto = {
	helpers: HelperInfo[],
	installer: Installer | null,
	/**  "macos" | "windows" | "linux" */
	platform: string,
};

/**  The four highlight colours. */
export type HighlightColor = "yellow" | "green" | "blue" | "pink";

/**  One place in a book where the words were found. */
export type Hit = {
	page: number | null,
	section: number | null,
	label: string | null,
	snippet: SnippetPart[],
};

/**  Summary of a finished import, for the report shown to the user. */
export type ImportFinished = {
	jobId: string,
	added: number,
	addedIds: string[],
	duplicates: DuplicateDto[],
	relinked: number,
	unsupported: number,
	failed: FailedFileDto[],
	warnings: string[],
};

export type ImportModeDto = "move" | "copy";

/**  Counts for Settings. */
export type IndexCounts = {
	books: number,
	withText: number,
	partial: number,
	noText: number,
	failed: number,
};

export type IndexStatusDto = {
	counts: IndexCounts,
	/**  Bytes on this computer. */
	size: number | null,
	running: boolean,
};

export type InkSettingsDto = {
	/**  "system" or "tesseract". */
	engine: string,
	/**  The system's recogniser, if this system has one. */
	system: string | null,
	tesseract: boolean,
};

/**  What will be run to install a helper, shown to the user first. */
export type InstallPlan = {
	helper: Helper,
	installer: Installer,
	/**  The command as a person would type it. */
	display: string,
	/**  The system asks for an administrator password. */
	needsAdmin: boolean,
};

/**  The package manager Libreri can use on this computer. */
export type Installer = "homebrew" | "winget" | "apt" | "dnf" | "pacman" | "zypper";

export type ItemFilter = {
	/**  A folder (with its subfolders) or a feed; neither: everything. */
	folder: string | null,
	feed: string | null,
	/**
	 *  "all", "unread", "downloaded", "library"; podcasts also
	 *  "inProgress" and "unplayed".
	 */
	show: string,
	/**  Items with this topic (arXiv: "cs.AI"). */
	topic: string | null,
	search: string | null,
	/**
	 *  Items still listed under "unread" (and "unplayed") though they were
	 *  just opened, so they do not vanish while being read.
	 */
	keep?: string[],
};

export type ItemsDto = {
	items: FeedItem[],
	/**  How many match, when more than are listed. */
	total: number,
	/**
	 *  Topics of the items shown by folder or feed (before the topic and
	 *  search filters), most common first.
	 */
	topics: TopicDto[],
};

/**  Progress of a background job, forwarded from `libreri-jobs`. */
export type JobEventPayload = {
	id: string,
	/**  "started" | "progress" | "finished" | "failed" | "cancelled" */
	kind: string,
	label: string | null,
	done: number | null,
	total: number | null,
	message: string | null,
};

/**  A video site Libreri knows how to embed without asking the site. */
export type KnownVideo = { provider: "youtube"; id: string } | { provider: "vimeo"; id: string; hash: string | null };

/**
 *  The books or folders changed (import, scan, rebuild). The interface
 *  refetches its lists.
 */
export type LibraryChanged = Record<string, never>;

export type LibrarySummary = {
	id: string,
	name: string,
	path: string,
	/**  `u32` is plenty for a book count and maps to a plain TypeScript number. */
	bookCount: number,
};

/**  Details of a link. */
export type LinkDetails = {
	url: string,
	kind: LinkKind,
	site: string,
	title: string | null,
	/**  The channel or author. */
	author: string | null,
	description: string | null,
	/**  Length in seconds, when the site says. */
	duration: number | null,
	/**  Where the video plays from (an https address for a frame). */
	embed: string | null,
	/**  YouTube or Vimeo: embedded by Libreri itself, with a start time. */
	video: KnownVideo | null,
	/**  A start time written in the address. */
	start: number | null,
};

export type LinkFileDto = {
	/**
	 *  The path in the library when the file is inside it (so the link
	 *  travels with the library), otherwise the full path.
	 */
	file: string,
	name: string,
	/**  "video" or "audio". */
	media: string,
	inLibrary: boolean,
};

/**  What a link points to. */
export type LinkKind = 
/**  A video that plays in the side panel. */
"video" | 
/**  A web page (opens in the browser; can be kept offline). */
"web";

export type LinkPreviewDto = {
	details: LinkDetails,
	/**  The picture as a data URL, to show before saving. */
	picture: string | null,
	/**  A web page whose readable part can be kept offline. */
	canCopy: boolean,
};

export type LinkSavedDto = {
	/**  The picture, in the profile's notes folder. */
	picture: string | null,
	/**  The offline copy of the page, in the profile's notes folder. */
	copy: string | null,
};

export type LocateResult = "linked" | 
/**  Another copy or edition: ask before using it. */
"differentFile";

export type Lookup = {
	/**  Best first. */
	candidates: Candidate[],
	errors: SourceError[],
};

/**  Progress of downloading the maths model. */
export type MathsDownload = {
	done: number | null,
	total: number | null,
	finished: boolean,
	error: string | null,
};

export type MathsSettingsDto = {
	/**  Turned on in Settings. */
	on: boolean,
	downloaded: boolean,
	sizeMb: number,
	downloading: boolean,
};

/**  A word that looks misspelt (UTF-16 offsets, end exclusive). */
export type Miss = {
	start: number,
	end: number,
	word: string,
};

/**  A model Libreri offers. */
export type ModelInfo = {
	id: string,
	name: string,
	/**  About how big the download is, in MB. */
	sizeMb: number,
	description: string,
	/**  Offered first; the bigger ones are in "More models". */
	recommended: boolean,
	downloaded: boolean,
};

export type NewProfile = {
	name: string,
	colour: string,
	kind: ProfileKind,
	pin: string | null,
};

export type NoteDto = {
	annotation: Annotation,
	bookTitle: string,
	fileType: FileType,
};

export type NotebookDto = {
	relPath: string,
	content: string,
};

export type NotebookEntryDto = {
	bookId: string | null,
	title: string,
	relPath: string,
	/**  Seconds since 1970. */
	modified: number | null,
	excerpt: string,
	words: number,
};

/**  "Make searchable" finished (or stopped). */
export type OcrFinished = {
	jobId: string,
	bookIds: string[],
	/**  Books done. */
	books: number,
	pagesRead: number,
	pagesFailed: number,
	errors: string[],
};

/**
 *  A language Tesseract can read on this computer, or could after a
 *  download.
 */
export type OcrLanguage = {
	code: string,
	name: string,
	/**  Came with Tesseract. */
	builtIn: boolean,
	/**  Downloaded by Libreri. */
	downloaded: boolean,
};

/**  Progress of downloading an OCR language. */
export type OcrLanguageDownload = {
	code: string,
	done: number | null,
	total: number | null,
	finished: boolean,
	error: string | null,
};

export type OcrLanguagesDto = {
	languages: OcrLanguage[],
	/**  Used when a book does not say its language. */
	defaults: string[],
	tesseract: boolean,
};

export type OnlineChange = {
	enabled: Source[] | null,
	fillOnImport: boolean | null,
};

export type OnlineSettingsDto = {
	sources: SourceInfo[],
	fillOnImport: boolean,
};

/**  One page of the result, in order. */
export type OutPage = 
/**
 *  A page of the book (1-based), turned by `rotate` degrees clockwise
 *  and cut to `crop` (x, y, w, h as fractions of the page as shown
 *  after turning).
 */
{ kind: "page"; page: number; rotate?: number; crop?: [(number | null), (number | null), (number | null), (number | null)] | null } | 
/**  A page of another PDF (`files[file]`). */
{ kind: "file"; file: number; page: number; rotate?: number; crop?: [(number | null), (number | null), (number | null), (number | null)] | null } | 
/**  An empty page, in points. */
{ kind: "blank"; width: number | null; height: number | null } | 
/**  A picture as a page (camera, phone, scanner or a picture file). */
{ kind: "picture"; src: string };

export type OutlineDto = {
	title: string,
	page: number | null,
	children: OutlineDto[],
};

export type PageBookDto = {
	/**  "comic" | "djvu" */
	kind: string,
	pages: number,
	/**  Width and height of each page (DjVu). */
	sizes: ([number, number])[],
	rightToLeft: boolean,
	outline: OutlineDto[],
	hasText: boolean,
};

/**
 *  Pages that belong together (1-based); `None` on one side means the page
 *  was added or removed.
 */
export type PagePair = {
	a: number | null,
	b: number | null,
};

export type PageScaleDto = {
	page: number,
	unit: string,
	perPoint: number | null,
};

/**
 *  One mark as an annotation. Positions are fractions of the page as
 *  shown (top-left origin); `width` is a fraction of the page width.
 */
export type PdfAnnot = {
	page: number,
	kind: PdfAnnotKind,
	/**  Libreri's id for the mark (kept as /NM). */
	id: string,
	/**  x, y, w, h around everything the mark draws. */
	rect: [(number | null), (number | null), (number | null), (number | null)],
	color: string,
	width?: number | null,
	/**  The note or text of the mark. */
	contents?: string | null,
	/**  Ink strokes; the two ends of a line. */
	points?: (([(number | null), (number | null)])[])[],
	/**  Boxes of a highlight, underline or strike-out. */
	rects?: ([(number | null), (number | null), (number | null), (number | null)])[],
	/**  How it looks. */
	ops: DrawOp[],
};

/**  The kind of PDF annotation a mark becomes. */
export type PdfAnnotKind = "ink" | "square" | "circle" | "line" | "freeText" | "note" | "stamp" | "highlight" | "underline" | "strikeOut";

/**  The phone page for paper pages was opened, or sent a photo. */
export type PhonePage = {
	/**  "opened" | "page" */
	kind: string,
	/**  The photo as a data: URL. */
	picture: string | null,
};

export type PhonePairingDto = {
	url: string,
	qrSvg: string,
	expiresIn: number,
};

/**  The phone page was opened, or it read a barcode. */
export type PhoneScan = {
	/**  "opened" | "scanned" */
	kind: string,
	scanned: ScannedDto | null,
};

export type PictureDto = {
	/**  A data URL, ready to place on a page. */
	src: string,
	width: number,
	height: number,
};

export type PlayerDto = {
	/**  The local page holding the site's player. */
	page: string,
	/**  The video's own page, for "Open in browser". */
	watch: string,
};

export type PodcastIndexDto = {
	/**  A key and secret are saved on this computer. */
	configured: boolean,
	/**  The key's last characters, to recognise it. */
	keyHint: string | null,
};

/**  A profile as the picker and Settings show it. Never includes hashes. */
export type ProfileDto = {
	id: string,
	name: string,
	colour: string,
	kind: ProfileKind,
	hasPin: boolean,
	/**  Kids: folders (relative to `Books/`) they may open. */
	allowedFolders: string[],
	lastUsed: string | null,
	/**  Seconds before another PIN may be tried (after wrong ones). */
	pinWait: number,
};

/**  What a profile may do. */
export type ProfileKind = 
/**  Created the library. Manages profiles and everything else. */
"owner" | 
/**  A grown-up: reads, notes, and organises the shared library. */
"standard" | 
/**
 *  Reads and makes notes, only in the folders the owner allows.
 *  Cannot import, edit details, move or delete books.
 */
"kids" | 
/**  Reads without an account. Nothing is kept after the guest leaves. */
"guest";

export type ProfileMappingDto = {
	archiveId: string,
	target: ProfileTargetDto,
};

/**  Where one archive profile's notes go. */
export type ProfileTargetDto = { kind: "existing"; profileId: string } | { kind: "new" } | { kind: "skip" };

/**  How much to shrink pictures. */
export type Quality = "high" | "medium" | "small";

/**
 *  What to look up. Identifiers are tried first; the title and author are
 *  used when there are none (or they find nothing).
 */
export type Query = {
	isbn?: string | null,
	doi?: string | null,
	arxivId?: string | null,
	title?: string | null,
	author?: string | null,
	/**
	 *  What kind of item it is, if known, so a comic goes to ComicVine and
	 *  a paper to Crossref.
	 */
	contentType?: ContentType | null,
};

/**  Where a reader is with a book. Personal: stored per profile. */
export type ReadingStatus = "none" | "wantToRead" | "reading" | "finished" | "abandoned";

export type RecentLibraryDto = {
	name: string,
	path: string,
	/**  False when the folder no longer exists or is no longer a library. */
	available: boolean,
};

/**  Boxes to black out on a page of the book (fractions of the shown page). */
export type Redaction = {
	page: number,
	boxes: ([(number | null), (number | null), (number | null), (number | null)])[],
	color?: string,
};

export type RefreshReport = {
	newItems: number,
	failed: number,
	downloaded: number,
	/**  Another check was already running. */
	busy: boolean,
};

export type RestoredLibrary = {
	library: LibrarySummary,
	jobId: string,
};

export type ScannedDto = {
	code: string,
	isbn13: string | null,
};

/**  The search index is being brought up to date in the background. */
export type SearchIndexProgress = {
	done: number,
	total: number,
	running: boolean,
};

/**
 *  Someone signed in or out (in any window). Every window checks who is
 *  signed in now, so locking locks them all.
 */
export type SessionChanged = {
	/**  The profile now signed in, if any. */
	profileId: string | null,
};

/**  Who is signed in and what they may do. */
export type SessionDto = {
	profile: ProfileDto,
	/**  The profile's interface preferences (JSON written by the interface). */
	prefs: string,
	canEditLibrary: boolean,
	canManageProfiles: boolean,
	/**  False for guests: nothing they do is kept. */
	keepsData: boolean,
};

export type SettingsDto = {
	theme: Theme,
	accent: string | null,
	recentLibraries: RecentLibraryDto[],
};

/**  A show found by a search. */
export type Show = {
	title: string,
	author: string | null,
	/**  The show's RSS feed. */
	feedUrl: string,
	artwork: string | null,
	categories: string[],
	episodes: number | null,
	/**  The newest episode (RFC 3339). */
	latest: string | null,
	about: string | null,
};

/**  Part of a snippet: matched words are marked. */
export type SnippetPart = {
	text: string,
	hit: boolean,
};

export type SortKey = "title" | "author" | "added" | "year" | "size" | "pages" | "lastOpened" | "rating";

/**  A place book details come from. */
export type Source = "openLibrary" | "googleBooks" | "crossref" | "openAlex" | "semanticScholar" | "arxiv" | "comicVine" | "isbndb";

/**  A source that could not be reached or answered with an error. */
export type SourceError = {
	source: Source,
	message: string,
};

/**  One source in Settings › Online details. */
export type SourceInfo = {
	source: Source,
	name: string,
	enabled: boolean,
	needsKey: boolean,
	/**  The end of the saved key ("…a1b2"); the key itself never leaves Rust. */
	keyHint: string | null,
};

/**
 *  Feeds (papers, articles) or podcasts: each has its own folders, feeds
 *  and items, in its own file.
 */
export type Space = "feeds" | "podcasts";

/**  Progress of downloading a speech model. */
export type SpeechModelDownload = {
	id: string,
	done: number | null,
	total: number | null,
	finished: boolean,
	error: string | null,
};

export type SpeechSettingsDto = {
	models: ModelInfo[],
	/**  The model in use: the one chosen, or the first downloaded. */
	model: string | null,
	language: string | null,
	transcribeNotes: boolean,
};

export type StorageDto = {
	books: number | null,
	notes: number | null,
	data: number | null,
};

/**  A source offered in "Suggested". */
export type Suggested = {
	title: string,
	url: string,
	/**  "Preprints", "Journals", "Science news", … */
	group: string,
	about: string,
};

export type SyncPointDto = {
	t: number | null,
	locator: string,
	progress: number | null,
	label: string | null,
	auto?: boolean,
};

export type TagCountDto = {
	name: string,
	count: number,
};

/**  One book whose words match. */
export type TextMatchDto = {
	book: BookDto,
	/**  Pages or passages that match. */
	total: number,
	/**  The best few, in reading order. */
	hits: Hit[],
};

/**
 *  The highlighted words with a little text before and after (W3C
 *  TextQuoteSelector).
 */
export type TextQuote = {
	exact?: string,
	prefix?: string,
	suffix?: string,
};

/**  Whether a book's words can be searched. */
export type TextState = 
/**  Every page (or the whole book) has text. */
"text" | 
/**  Some pages have text, some are scans without it. */
"partial" | 
/**  A scan without text: OCR can make it searchable. */
"noText" | 
/**  A format without words (comics, audio). */
"noWords" | 
/**  The text could not be read (damaged, DRM, a helper is missing). */
"failed";

export type TextStatusDto = {
	/**  `null` while the book waits to be indexed. */
	state: TextState | null,
	pages: number,
	emptyPages: number,
	ocrPages: number,
	ocrLanguages: string[],
	canOcr: boolean,
	message: string | null,
	/**  Languages to read it in: the book's own, else the usual ones. */
	suggestedLanguages: string[],
};

export type Theme = "system" | "light" | "dark" | "highContrast";

export type TopicDto = {
	code: string,
	/**  arXiv's name for it, when it is an arXiv category. */
	name: string | null,
	count: number,
};

export type UnsearchableDto = {
	id: string,
	state: TextState,
};

export type VersionDto = {
	id: string,
	fileName: string,
	savedAt: string,
	reason: string,
	size: number | null,
};

export type VersionsUsage = {
	count: number,
	bytes: number | null,
};

/**  A voice eSpeak NG offers. */
export type Voice = {
	/**  What to pass to `-v` (a language such as "en-gb"). */
	id: string,
	name: string,
	lang: string,
};

export type VoiceNoteDto = {
	/**  The recording, in the library (`Notes/<profile>/Voice notes/…`). */
	path: string,
	/**  Seconds. */
	duration: number | null,
};

export type WordDto = {
	text: string,
	/**  x, y, width, height as fractions of the page from the top left. */
	rect: [(number | null), (number | null), (number | null), (number | null)],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

