// Generated by tauri-specta from the Rust commands. Do not edit.
// Regenerate with: pnpm gen:ipc

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Version and platform, for the About screen and diagnostics. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**
	 *  Opens a web link in the system browser. Only `http`, `https` and
	 *  `mailto` links are allowed.
	 */
	openExternalUrl: (url: string) => typedError<null, AppError>(__TAURI_INVOKE("open_external_url", { url })),
	getSettings: () => __TAURI_INVOKE<SettingsDto>("get_settings"),
	setTheme: (theme: Theme) => typedError<SettingsDto, AppError>(__TAURI_INVOKE("set_theme", { theme })),
	setAccent: (accent: string | null) => typedError<SettingsDto, AppError>(__TAURI_INVOKE("set_accent", { accent })),
	forgetRecentLibrary: (path: string) => typedError<SettingsDto, AppError>(__TAURI_INVOKE("forget_recent_library", { path })),
	/**
	 *  What a book would be looked up by (its identifiers, or ones found in
	 *  its pages), to fill the search form.
	 */
	detailsQuery: (id: string) => typedError<Query, AppError>(__TAURI_INVOKE("details_query", { id })),
	/**
	 *  Asks the online sources about a book. `query` is the reader's own
	 *  search; without it the book's details are used.
	 */
	findDetails: (id: string, query: {
	isbn?: string | null,
	doi?: string | null,
	arxivId?: string | null,
	title?: string | null,
	author?: string | null,
	/**
	 *  What kind of item it is, if known, so a comic goes to ComicVine and
	 *  a paper to Crossref.
	 */
	contentType?: ContentType | null,
} | null) => typedError<Lookup, AppError>(__TAURI_INVOKE("find_details", { id, query })),
	/**  Saves the details picked in the merge screen, and the picked cover. */
	applyDetails: (id: string, metadata: BookMetadata, coverUrl: string | null) => typedError<AppliedDetails, AppError>(__TAURI_INVOKE("apply_details", { id, metadata, coverUrl })),
	/**
	 *  A cover from a source as a data: URL, so the interface can show it
	 *  without loading images from the internet itself.
	 */
	coverPreview: (url: string) => typedError<string, AppError>(__TAURI_INVOKE("cover_preview", { url })),
	/**
	 *  Fills in missing details of many books in the background. Returns the
	 *  job id; the result arrives as a `DetailsFilled` event.
	 */
	fillMissingDetails: (ids: string[]) => typedError<string, AppError>(__TAURI_INVOKE("fill_missing_details", { ids })),
	getOnlineSettings: () => __TAURI_INVOKE<OnlineSettingsDto>("get_online_settings"),
	setOnlineSettings: (change: OnlineChange) => typedError<OnlineSettingsDto, AppError>(__TAURI_INVOKE("set_online_settings", { change })),
	/**
	 *  Saves (or, with `None`, removes) the reader's key for a source. Saving
	 *  a key also turns the source on.
	 */
	setSourceKey: (source: Source, key: string | null) => typedError<OnlineSettingsDto, AppError>(__TAURI_INVOKE("set_source_key", { source, key })),
	/**
	 *  Reads a barcode from a picture (a camera frame), sent as a data: URL or
	 *  base64. Returns nothing if there is no readable barcode.
	 */
	scanPicture: (data: string) => typedError<{
	code: string,
	isbn13: string | null,
} | null, AppError>(__TAURI_INVOKE("scan_picture", { data })),
	/**  Reads a barcode from a picture file the reader chose. */
	scanPictureFile: (path: string) => typedError<{
	code: string,
	isbn13: string | null,
} | null, AppError>(__TAURI_INVOKE("scan_picture_file", { path })),
	/**
	 *  Starts the phone page (replacing any earlier one). Scans arrive as
	 *  `PhoneScan` events.
	 */
	startPhoneScan: () => typedError<PhonePairingDto, AppError>(__TAURI_INVOKE("start_phone_scan")),
	/**  Stops the phone page. */
	stopPhoneScan: () => __TAURI_INVOKE<void>("stop_phone_scan"),
	/**  Creates a new library in `path` and opens it. */
	createLibrary: (path: string, name: string | null) => typedError<LibrarySummary, AppError>(__TAURI_INVOKE("create_library", { path, name })),
	/**
	 *  Opens an existing library. `force` takes over a lock left by another
	 *  computer, after the user has confirmed.
	 */
	openLibrary: (path: string, force: boolean) => typedError<LibrarySummary, AppError>(__TAURI_INVOKE("open_library", { path, force })),
	closeLibrary: () => __TAURI_INVOKE<void>("close_library"),
	currentLibrary: () => __TAURI_INVOKE<{
	id: string,
	name: string,
	path: string,
	/**  `u32` is plenty for a book count and maps to a plain TypeScript number. */
	bookCount: number,
} | null>("current_library"),
	/**  Tells the Welcome screen what the chosen folder contains. */
	inspectFolder: (path: string) => __TAURI_INVOKE<FolderKind>("inspect_folder", { path }),
	/**
	 *  Checks the library folder for changes now (the watcher does this
	 *  automatically; this is the manual "Refresh").
	 */
	rescanLibrary: () => typedError<string | null, AppError>(__TAURI_INVOKE("rescan_library")),
	/**  Rebuilds the database from the book files and JSON sidecars. */
	rebuildLibraryIndex: () => typedError<string, AppError>(__TAURI_INVOKE("rebuild_library_index")),
	/**  Stops a running import or scan at the next file. */
	cancelJob: (id: string) => __TAURI_INVOKE<boolean>("cancel_job", { id }),
	listBooks: (query: BookQuery) => typedError<BookDto[], AppError>(__TAURI_INVOKE("list_books", { query })),
	getBook: (id: string) => typedError<BookDto, AppError>(__TAURI_INVOKE("get_book", { id })),
	libraryFacets: () => typedError<FacetsDto, AppError>(__TAURI_INVOKE("library_facets")),
	/**
	 *  Saves edited details. Refuses invalid ISBNs, an empty title, etc. with a
	 *  message that says what to fix.
	 */
	updateBook: (id: string, metadata: BookMetadata) => typedError<BookDto, AppError>(__TAURI_INVOKE("update_book", { id, metadata })),
	/**  Saves the current profile's reading status, rating and favourite flag. */
	setBookState: (id: string, user: BookUserState) => typedError<BookDto, AppError>(__TAURI_INVOKE("set_book_state", { id, user })),
	/**  Moves books into a folder (relative to `Books/`). Returns how many moved. */
	moveBooks: (ids: string[], folder: string) => typedError<number, AppError>(__TAURI_INVOKE("move_books", { ids, folder })),
	/**  Moves books to the system trash. Returns how many were removed. */
	trashBooks: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("trash_books", { ids })),
	/**
	 *  Stores a cover sent by the interface (base64 of a JPEG or PNG), such as
	 *  the first page of a PDF rendered with PDF.js.
	 */
	saveCover: (id: string, imageBase64: string) => typedError<null, AppError>(__TAURI_INVOKE("save_cover", { id, imageBase64 })),
	/**
	 *  Opens the book in the system's default app (until Libreri's own reader
	 *  arrives in Phase 2).
	 */
	openBookExternally: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("open_book_externally", { id })),
	/**  Shows the book's file in Finder / Explorer / the file manager. */
	revealBook: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("reveal_book", { id })),
	listFolders: () => typedError<FolderDto[], AppError>(__TAURI_INVOKE("list_folders")),
	/**  Creates `name` inside `parent`; returns the new folder's path. */
	createFolder: (parent: string, name: string) => typedError<string, AppError>(__TAURI_INVOKE("create_folder", { parent, name })),
	renameFolder: (path: string, name: string) => typedError<string, AppError>(__TAURI_INVOKE("rename_folder", { path, name })),
	moveFolder: (path: string, parent: string) => typedError<string, AppError>(__TAURI_INVOKE("move_folder", { path, parent })),
	/**
	 *  Moves a folder and its books to the system trash; returns the number of
	 *  books removed.
	 */
	trashFolder: (path: string) => typedError<number, AppError>(__TAURI_INVOKE("trash_folder", { path })),
	revealFolder: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("reveal_folder", { path })),
	/**
	 *  Starts importing files and folders into `folder`. Returns the job id;
	 *  progress arrives as job events and the summary as `ImportFinished`.
	 */
	importPaths: (paths: string[], folder: string, mode: ImportModeDto) => typedError<string, AppError>(__TAURI_INVOKE("import_paths", { paths, folder, mode })),
	/**  Where the current profile stopped reading (JSON), if anywhere. */
	getPosition: (id: string) => typedError<string | null, AppError>(__TAURI_INVOKE("get_position", { id })),
	savePosition: (id: string, locator: string, progress: number | null) => typedError<null, AppError>(__TAURI_INVOKE("save_position", { id, locator, progress })),
	listAnnotations: (id: string) => typedError<Annotation[], AppError>(__TAURI_INVOKE("list_annotations", { id })),
	/**  Adds or updates a highlight or bookmark; returns it with timestamps set. */
	saveAnnotation: (annotation: Annotation) => typedError<Annotation, AppError>(__TAURI_INVOKE("save_annotation", { annotation })),
	deleteAnnotation: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_annotation", { id })),
	/**  The Markdown notebook for a book, created on first use. */
	getNotebook: (id: string) => typedError<NotebookDto, AppError>(__TAURI_INVOKE("get_notebook", { id })),
	saveNotebook: (id: string, content: string) => typedError<NotebookDto, AppError>(__TAURI_INVOKE("save_notebook", { id, content })),
	/**  The reader tabs that were open last time (JSON written by the interface). */
	getSession: () => typedError<string | null, AppError>(__TAURI_INVOKE("get_session")),
	saveSession: (session: string) => typedError<null, AppError>(__TAURI_INVOKE("save_session", { session })),
	listProfiles: () => typedError<ProfileDto[], AppError>(__TAURI_INVOKE("list_profiles")),
	/**  The signed-in profile, or nothing when the profile picker should show. */
	currentSession: () => typedError<{
	profile: ProfileDto,
	/**  The profile's interface preferences (JSON written by the interface). */
	prefs: string,
	canEditLibrary: boolean,
	canManageProfiles: boolean,
	/**  False for guests: nothing they do is kept. */
	keepsData: boolean,
} | null, AppError>(__TAURI_INVOKE("current_session")),
	signIn: (id: string, pin: string | null) => typedError<SessionDto, AppError>(__TAURI_INVOKE("sign_in", { id, pin })),
	/**  Locks the library and goes back to the profile picker. */
	signOut: () => typedError<null, AppError>(__TAURI_INVOKE("sign_out")),
	createProfile: (profile: NewProfile) => typedError<ProfileDto, AppError>(__TAURI_INVOKE("create_profile", { profile })),
	updateProfile: (id: string, name: string, colour: string, kind: ProfileKind) => typedError<ProfileDto, AppError>(__TAURI_INVOKE("update_profile", { id, name, colour, kind })),
	/**
	 *  Sets, changes or removes a PIN. Returns the owner's new recovery code,
	 *  which the interface shows once.
	 */
	setProfilePin: (id: string, currentPin: string | null, newPin: string | null) => typedError<string | null, AppError>(__TAURI_INVOKE("set_profile_pin", { id, currentPin, newPin })),
	/**
	 *  Resets the owner's forgotten PIN with the recovery code and signs in.
	 *  Returns the next recovery code.
	 */
	recoverOwner: (recoveryCode: string, newPin: string) => typedError<string, AppError>(__TAURI_INVOKE("recover_owner", { recoveryCode, newPin })),
	deleteProfile: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_profile", { id })),
	setAllowedFolders: (id: string, folders: string[]) => typedError<ProfileDto, AppError>(__TAURI_INVOKE("set_allowed_folders", { id, folders })),
	/**  Saves the signed-in profile's interface preferences (JSON). */
	savePrefs: (prefs: string) => typedError<null, AppError>(__TAURI_INVOKE("save_prefs", { prefs })),
	listCollections: () => typedError<CollectionDto[], AppError>(__TAURI_INVOKE("list_collections")),
	/**  Adds (empty `id`) or updates a smart collection. */
	saveCollection: (id: string, name: string, query: BookQuery) => typedError<CollectionDto, AppError>(__TAURI_INVOKE("save_collection", { id, name, query })),
	deleteCollection: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_collection", { id })),
	/**  Applies one edit to many books. Returns how many changed. */
	bulkEditBooks: (ids: string[], edit: BulkEdit) => typedError<number, AppError>(__TAURI_INVOKE("bulk_edit_books", { ids, edit })),
	renameTag: (from: string, to: string) => typedError<number, AppError>(__TAURI_INVOKE("rename_tag", { from, to })),
	mergeTags: (sources: string[], into: string) => typedError<number, AppError>(__TAURI_INVOKE("merge_tags", { sources, into })),
	deleteTag: (tag: string) => typedError<number, AppError>(__TAURI_INVOKE("delete_tag", { tag })),
	renameCategory: (from: string, to: string) => typedError<number, AppError>(__TAURI_INVOKE("rename_category", { from, to })),
	deleteCategory: (path: string) => typedError<number, AppError>(__TAURI_INVOKE("delete_category", { path })),
	/**  Groups of tags that look like the same thing. */
	similarTags: () => typedError<TagCountDto[][], AppError>(__TAURI_INVOKE("similar_tags")),
	/**  All highlights, comments and bookmarks of the signed-in profile. */
	listAllNotes: () => typedError<NoteDto[], AppError>(__TAURI_INVOKE("list_all_notes")),
	/**  All Markdown notes in the signed-in profile's notes folder. */
	listNotebooks: () => typedError<NotebookEntryDto[], AppError>(__TAURI_INVOKE("list_notebooks")),
	readNote: (relPath: string) => typedError<string, AppError>(__TAURI_INVOKE("read_note", { relPath })),
	writeNote: (relPath: string, content: string) => typedError<null, AppError>(__TAURI_INVOKE("write_note", { relPath, content })),
	/**  Starts a note that is not about one book. Returns its path. */
	createNote: (title: string) => typedError<string, AppError>(__TAURI_INVOKE("create_note", { title })),
	/**  Shows the signed-in profile's notes folder in the file manager. */
	revealNotesFolder: () => typedError<string, AppError>(__TAURI_INVOKE("reveal_notes_folder")),
	/**  How much space the library's folders use, in bytes. */
	libraryStorage: () => typedError<StorageDto, AppError>(__TAURI_INVOKE("library_storage")),
};

/** Events */
export const events = {
	detailsFilled: makeEvent<DetailsFilled>("details-filled"),
	importFinished: makeEvent<ImportFinished>("import-finished"),
	jobEventPayload: makeEvent<JobEventPayload>("job-event-payload"),
	libraryChanged: makeEvent<LibraryChanged>("library-changed"),
	phoneScan: makeEvent<PhoneScan>("phone-scan"),
	sessionChanged: makeEvent<SessionChanged>("session-changed"),
};

/* Types */
export type Annotation = {
	/**  UUID, created by whoever makes the annotation. */
	id: string,
	bookId: BookId,
	kind: AnnotationKind,
	color: HighlightColor | null,
	/**  Format-specific position as JSON, e.g. `{"type":"pdf","page":4,…}`. */
	locator: string,
	quote: TextQuote | null,
	/**  The comment written on a highlight, or a bookmark's name. */
	note: string | null,
	/**  Where it is, for people: "p. 4" or a chapter title. */
	label: string | null,
	/**  0.0–1.0 through the book, for sorting. */
	position: number | null,
	createdAt: string,
	modifiedAt: string,
};

export type AnnotationKind = "highlight" | "bookmark";

export type AppError = {
	kind: AppErrorKind,
	message: string,
};

export type AppErrorKind = "notALibrary" | "alreadyALibrary" | "folderNotEmpty" | "formatTooNew" | "lockedElsewhere" | "alreadyOpenHere" | "storage" | "io" | 
/**  No library is open (the window is on the Welcome screen). */
"noLibrary" | "notFound" | 
/**  Something the user typed was refused; the message says why. */
"invalidInput" | "nameTaken" | "trash" | "cancelled" | 
/**  Nobody is signed in: show the profile picker. */
"signedOut" | 
/**  The PIN was wrong; the message says how many tries are left. */
"wrongPin" | 
/**  Too many wrong PINs; the message says how long to wait. */
"pinLocked" | 
/**  The signed-in profile may not do this (Kids, Guest, not the owner). */
"notAllowed";

export type AppInfo = {
	version: string,
	platform: string,
};

export type AppliedDetails = {
	book: BookDto,
	/**  Why the picked cover could not be used, if it could not. */
	coverError: string | null,
};

/**  Everything about one book in the library. */
export type Book = {
	id: BookId,
	/**  Relative to the library root, with `/` separators: "Books/Physics/a.pdf". */
	relPath: string,
	fileType: FileType,
	/**  Sent to TypeScript as a number; no file comes near 2^53 bytes. */
	fileSize: number,
	hasCover: boolean,
	/**  The file could not be found at `rel_path` during the last scan. */
	missing: boolean,
	addedAt: string,
	modifiedAt: string,
	metadata: BookMetadata,
	user: BookUserState,
};

/**
 *  A book as the interface sees it: the stored record plus the paths of
 *  its images (served by `book://`) and its folder.
 */
export type BookDto = {
	/**  Folder relative to `Books/` ("" = top level). */
	folder: string,
	thumbnail: string | null,
	cover: string | null,
} & Book;

/**  Identifier of a book: the lowercase hex BLAKE3 hash of the file content. */
export type BookId = string;

/**
 *  Bibliographic details shared by every profile. This is what the details
 *  panel edits and what the JSON sidecar stores.
 */
export type BookMetadata = {
	title?: string,
	subtitle?: string | null,
	authors?: string[],
	/**  Editors, translators, illustrators — free text such as "Jane Smith (translator)". */
	contributors?: string[],
	about?: string | null,
	tags?: string[],
	/**  Hierarchical, written as paths: "Science/Physics". */
	categories?: string[],
	year?: number | null,
	publisher?: string | null,
	pages?: number | null,
	isbn13?: string | null,
	isbn10?: string | null,
	edition?: string | null,
	/**  BCP 47 code such as "en" or "de". */
	language?: string | null,
	contentType?: ContentType,
	series?: string | null,
	seriesNumber?: number | null,
	doi?: string | null,
	arxivId?: string | null,
	journal?: string | null,
	volume?: string | null,
	issue?: string | null,
	url?: string | null,
};

/**  A filter for the book list. Empty lists mean "any". */
export type BookQuery = {
	/**  Folder relative to `Books/` ("" = top level). `None` = whole library. */
	folder?: string | null,
	/**  With `folder`, also include books in its subfolders. */
	includeSubfolders?: boolean,
	/**  Free text matched against title, authors, tags, ISBN, … */
	search?: string | null,
	fileTypes?: FileType[],
	contentTypes?: ContentType[],
	/**  Books must have every one of these tags. */
	tags?: string[],
	/**  Books must be in this category or one below it. */
	category?: string | null,
	status?: ReadingStatus | null,
	favoritesOnly?: boolean,
	/**  `Some(true)` only audiobooks, `Some(false)` hides them. */
	audio?: boolean | null,
	missingOnly?: boolean,
	sort?: SortKey,
	descending?: boolean,
};

/**  Personal state of one profile for one book. */
export type BookUserState = {
	status?: ReadingStatus,
	/**  0 = not rated, 1–5 stars. */
	rating?: number,
	favorite?: boolean,
	/**  0.0–1.0. */
	progress?: number | null,
	lastOpened?: string | null,
};

/**
 *  Changes applied to many books at once. `None` leaves a field alone;
 *  `Some("")` clears a text field.
 */
export type BulkEdit = {
	/**  Replaces the authors (an empty list removes them). */
	authors?: string[] | null,
	publisher?: string | null,
	/**  A year, or "" to clear. */
	year?: string | null,
	language?: string | null,
	contentType?: ContentType | null,
	series?: string | null,
	/**  Number the books 1, 2, 3… in the order given. */
	numberSeries?: boolean,
	addTags?: string[],
	removeTags?: string[],
	addCategories?: string[],
	removeCategories?: string[],
};

/**  One source's idea of what the book is. */
export type Candidate = {
	source: Source,
	/**  The source's own id ("OL7353617M", "10.1038/nature14539"). */
	sourceId: string,
	/**  The page about it on the source's website. */
	link: string | null,
	metadata: BookMetadata,
	coverUrl: string | null,
	/**  How well it matches the query, 0–1. An identifier match is 1. */
	score: number | null,
};

export type CollectionDto = {
	id: string,
	name: string,
	query: BookQuery,
};

/**  What kind of document a book is. Chosen by the user; guessed on import. */
export type ContentType = "book" | "textbook" | "researchPaper" | "conferencePaper" | "preprint" | "thesis" | "lectureNotes" | "slides" | "technicalReport" | "whitePaper" | "manual" | "reference" | "standard" | "magazine" | "article" | "comic" | "cheatSheet" | "personalNotes" | "audiobook" | "other";

export type CountDto<T> = {
	value: T,
	count: number,
};

/**  "Fill in missing details" finished (by hand, or after an import). */
export type DetailsFilled = {
	jobId: string,
	filled: string[],
	/**  Books with no sure match, to look up one by one. */
	unsure: string[],
	unchanged: number,
	failed: FailedFileDto[],
};

export type DuplicateDto = {
	file: string,
	existingTitle: string,
	existingId: string,
};

/**  Counts for the sidebar and the filter menus. */
export type FacetsDto = {
	total: number,
	wantToRead: number,
	reading: number,
	finished: number,
	favorites: number,
	audio: number,
	missing: number,
	fileTypes: CountDto<FileType>[],
	contentTypes: CountDto<ContentType>[],
	tags: CountDto<string>[],
	categories: CountDto<string>[],
};

export type FailedFileDto = {
	file: string,
	reason: string,
};

/**  Every file format Libreri accepts, detected from the file extension. */
export type FileType = "pdf" | "epub" | "mobi" | "azw3" | "fb2" | "txt" | "md" | "djvu" | "cbz" | "cbr" | "cb7" | "cba" | "cbt" | "mp3" | "m4b" | "m4a" | "aac" | "ogg" | "opus" | "flac";

export type FolderDto = {
	name: string,
	/**  Relative to `Books/`, `/`-separated. */
	path: string,
	bookCount: number,
	totalCount: number,
	children: FolderDto[],
};

/**
 *  What a folder the user picked contains, so the Welcome screen can offer
 *  the right action.
 */
export type FolderKind = "missing" | "empty" | "library" | "otherFiles";

/**  The four highlight colours. */
export type HighlightColor = "yellow" | "green" | "blue" | "pink";

/**  Summary of a finished import, for the report shown to the user. */
export type ImportFinished = {
	jobId: string,
	added: number,
	addedIds: string[],
	duplicates: DuplicateDto[],
	relinked: number,
	unsupported: number,
	failed: FailedFileDto[],
	warnings: string[],
};

export type ImportModeDto = "move" | "copy";

/**  Progress of a background job, forwarded from `libreri-jobs`. */
export type JobEventPayload = {
	id: string,
	/**  "started" | "progress" | "finished" | "failed" | "cancelled" */
	kind: string,
	label: string | null,
	done: number | null,
	total: number | null,
	message: string | null,
};

/**
 *  The books or folders changed (import, scan, rebuild). The interface
 *  refetches its lists.
 */
export type LibraryChanged = Record<string, never>;

export type LibrarySummary = {
	id: string,
	name: string,
	path: string,
	/**  `u32` is plenty for a book count and maps to a plain TypeScript number. */
	bookCount: number,
};

export type Lookup = {
	/**  Best first. */
	candidates: Candidate[],
	errors: SourceError[],
};

export type NewProfile = {
	name: string,
	colour: string,
	kind: ProfileKind,
	pin: string | null,
};

export type NoteDto = {
	annotation: Annotation,
	bookTitle: string,
	fileType: FileType,
};

export type NotebookDto = {
	relPath: string,
	content: string,
};

export type NotebookEntryDto = {
	bookId: string | null,
	title: string,
	relPath: string,
	/**  Seconds since 1970. */
	modified: number | null,
	excerpt: string,
	words: number,
};

export type OnlineChange = {
	enabled: Source[] | null,
	fillOnImport: boolean | null,
};

export type OnlineSettingsDto = {
	sources: SourceInfo[],
	fillOnImport: boolean,
};

export type PhonePairingDto = {
	url: string,
	qrSvg: string,
	expiresIn: number,
};

/**  The phone page was opened, or it read a barcode. */
export type PhoneScan = {
	/**  "opened" | "scanned" */
	kind: string,
	scanned: ScannedDto | null,
};

/**  A profile as the picker and Settings show it. Never includes hashes. */
export type ProfileDto = {
	id: string,
	name: string,
	colour: string,
	kind: ProfileKind,
	hasPin: boolean,
	/**  Kids: folders (relative to `Books/`) they may open. */
	allowedFolders: string[],
	lastUsed: string | null,
	/**  Seconds before another PIN may be tried (after wrong ones). */
	pinWait: number,
};

/**  What a profile may do. */
export type ProfileKind = 
/**  Created the library. Manages profiles and everything else. */
"owner" | 
/**  A grown-up: reads, notes, and organises the shared library. */
"standard" | 
/**
 *  Reads and makes notes, only in the folders the owner allows.
 *  Cannot import, edit details, move or delete books.
 */
"kids" | 
/**  Reads without an account. Nothing is kept after the guest leaves. */
"guest";

/**
 *  What to look up. Identifiers are tried first; the title and author are
 *  used when there are none (or they find nothing).
 */
export type Query = {
	isbn?: string | null,
	doi?: string | null,
	arxivId?: string | null,
	title?: string | null,
	author?: string | null,
	/**
	 *  What kind of item it is, if known, so a comic goes to ComicVine and
	 *  a paper to Crossref.
	 */
	contentType?: ContentType | null,
};

/**  Where a reader is with a book. Personal: stored per profile. */
export type ReadingStatus = "none" | "wantToRead" | "reading" | "finished" | "abandoned";

export type RecentLibraryDto = {
	name: string,
	path: string,
	/**  False when the folder no longer exists or is no longer a library. */
	available: boolean,
};

export type ScannedDto = {
	code: string,
	isbn13: string | null,
};

/**
 *  Someone signed in or out (in any window). Every window checks who is
 *  signed in now, so locking locks them all.
 */
export type SessionChanged = {
	/**  The profile now signed in, if any. */
	profileId: string | null,
};

/**  Who is signed in and what they may do. */
export type SessionDto = {
	profile: ProfileDto,
	/**  The profile's interface preferences (JSON written by the interface). */
	prefs: string,
	canEditLibrary: boolean,
	canManageProfiles: boolean,
	/**  False for guests: nothing they do is kept. */
	keepsData: boolean,
};

export type SettingsDto = {
	theme: Theme,
	accent: string | null,
	recentLibraries: RecentLibraryDto[],
};

export type SortKey = "title" | "author" | "added" | "year" | "size" | "pages" | "lastOpened" | "rating";

/**  A place book details come from. */
export type Source = "openLibrary" | "googleBooks" | "crossref" | "openAlex" | "semanticScholar" | "arxiv" | "comicVine" | "isbndb";

/**  A source that could not be reached or answered with an error. */
export type SourceError = {
	source: Source,
	message: string,
};

/**  One source in Settings › Online details. */
export type SourceInfo = {
	source: Source,
	name: string,
	enabled: boolean,
	needsKey: boolean,
	/**  The end of the saved key ("…a1b2"); the key itself never leaves Rust. */
	keyHint: string | null,
};

export type StorageDto = {
	books: number | null,
	notes: number | null,
	data: number | null,
};

export type TagCountDto = {
	name: string,
	count: number,
};

/**
 *  The highlighted words with a little text before and after (W3C
 *  TextQuoteSelector).
 */
export type TextQuote = {
	exact?: string,
	prefix?: string,
	suffix?: string,
};

export type Theme = "system" | "light" | "dark" | "highContrast";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

