// Writes docs/third-party-licenses.md: every library Libreri is built from
// (Rust crates and the interface's packages), with its licence and home.
// Run with `node scripts/third-party.mjs` after changing dependencies.
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const meta = JSON.parse(
  execSync("cargo metadata --format-version 1 --locked", { maxBuffer: 1 << 28 }).toString(),
);
const ours = new Set(meta.workspace_members);
const rust = meta.packages
  .filter((p) => !ours.has(p.id))
  .map((p) => ({
    name: p.name,
    version: p.version,
    license: (p.license ?? "see its repository").replace(/\//g, " OR "),
    home: p.repository ?? p.homepage ?? `https://crates.io/crates/${p.name}`,
  }))
  .sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));

const npmByLicence = JSON.parse(
  execSync("pnpm licenses list --prod --json", { maxBuffer: 1 << 26 }).toString(),
);
// Installed with Mermaid but left out of the app (see src/lib/stubs/elk.ts).
const LEFT_OUT = new Set(["elkjs"]);
// Packages whose package.json does not say, checked by hand.
const CHECKED = { khroma: "MIT" };
const npm = Object.values(npmByLicence)
  .flat()
  .filter((p) => !p.name.startsWith("@libreri/") && !LEFT_OUT.has(p.name))
  .map((p) => ({
    name: p.name,
    version: p.versions.join(", "),
    license: p.license === "Unknown" ? (CHECKED[p.name] ?? "see its repository") : p.license,
    home: p.homepage ?? `https://www.npmjs.com/package/${p.name}`,
  }))
  .sort((a, b) => a.name.localeCompare(b.name));

const count = (list) => {
  const c = new Map();
  for (const p of list) c.set(p.license, (c.get(p.license) ?? 0) + 1);
  return [...c.entries()].sort((a, b) => b[1] - a[1]);
};
const table = (list) =>
  ["| Package | Version | Licence |", "|---|---|---|"]
    .concat(list.map((p) => `| [${p.name}](${p.home}) | ${p.version} | ${p.license} |`))
    .join("\n");

const md = `# Third-party licences

Libreri is free software under the [GNU General Public License v3.0 or later](../LICENSE). It is built on the work of many others; this page lists every library compiled into it, with its licence. All of them are compatible with the GPL. (elkjs, which Mermaid can use for one diagram layout, is under the Eclipse Public License and is left out of Libreri for that reason.)

This file is generated by \`node scripts/third-party.mjs\`; do not edit it by hand.

## Not part of Libreri, used alongside it

These run as separate programs or are downloaded only when you ask; they keep their own licences.

| What | Licence | Used for |
|---|---|---|
| [DjVuLibre](https://djvu.sourceforge.net/) | GPL-2.0-or-later | DjVu books (helper program) |
| [Tesseract](https://github.com/tesseract-ocr/tesseract) | Apache-2.0 | OCR (helper program) |
| [unar](https://theunarchiver.com/command-line) | LGPL-2.1-or-later | CBR, CB7 and CBA comics (helper program) |
| [eSpeak NG](https://github.com/espeak-ng/espeak-ng) | GPL-3.0-or-later | Read aloud and natural voices (helper program) |
| [ONNX Runtime](https://github.com/microsoft/onnxruntime) | MIT | Runs the natural voices (download) |
| [Kokoro-82M](https://huggingface.co/hexgrad/Kokoro-82M) | Apache-2.0 | Natural voices (download) |
| [Piper voices](https://huggingface.co/rhasspy/piper-voices) | Each voice's own; only voices free for anyone are offered | Natural voices (download) |
| [whisper.cpp models](https://huggingface.co/ggerganov/whisper.cpp) | MIT | Voice notes, dictation, transcripts (download) |
| [PaddleOCR-VL](https://huggingface.co/PaddlePaddle/PaddleOCR-VL) | Apache-2.0 | Reading scanned pages (download) |
| [pix2tex](https://github.com/lukas-blecher/LaTeX-OCR) | MIT | Maths from pictures (download) |
| Hunspell dictionaries | Each dictionary's own (shown before download) | Spell check (download) |
| Fonts: Geist, Geist Mono | OFL-1.1 | The interface |

## Licences at a glance

**Rust crates (${rust.length}):** ${count(rust).map(([l, n]) => `${l} (${n})`).join(", ")}.

**Interface packages (${npm.length}):** ${count(npm).map(([l, n]) => `${l} (${n})`).join(", ")}.

## Interface packages

${table(npm)}

## Rust crates

${table(rust)}
`;
writeFileSync(new URL("../docs/third-party-licenses.md", import.meta.url), md);
console.log(`docs/third-party-licenses.md: ${rust.length} crates, ${npm.length} packages`);
